---

# File: inventory/trident/nodes.yml

trident:
  vars:
      # Default site settings. Over-ride specifics below
      trident_nginx_http_listen_port: 80
      trident_nginx_https_listen_port: 443
      trident_http_listen_port: 8333
      trident_sysadmin_user: 'trident'

      trident_db_name: 'trident'
      trident_db_user: 'trident'
      trident_db_listen_port: 5432

      # Several trident packages (server, cli, all) share the same
      # version number. Related packages are in the same directory, too.
      trident_download_dir: 'https://github.com/tridentli/trident/releases/download/v{{ trident_version }}'

      # Trident components are all loaded at once as a bundle
      trident_dist_bundle:
        - { 'url': '{{ trident_server_disturl }}', 'sha256sum': '{{ trident_server_sha256sum }}' }
        - { 'url': '{{ trident_cli_disturl }}', 'sha256sum': '{{ trident_cli_sha256sum }}' }
        - { 'url': '{{ trident_all_disturl }}', 'sha256sum': '{{ trident_all_sha256sum }}' }
        - { 'url': '{{ pitchfork_disturl }}', 'sha256sum': '{{ pitchfork_sha256sum }}' }
        - { 'url': '{{ trident_wikiexport_disturl }}', 'sha256sum': '{{ trident_wikiexport_sha256sum }}' }

      trident_cli_version: '{{ trident_version }}'
      trident_cli_archive: 'trident-cli_{{ trident_cli_version }}_amd64.deb'
      trident_cli_disturl: '{{ trident_download_dir }}/{{ trident_cli_archive }}'
      trident_cli_sha256sum: '15f11c986493a67e85aa9cffe6719a15a8c6a65b739a2b0adf62ce61e53f4203'
      trident_cli_opts: ''

      trident_server_version: '{{ trident_version }}'
      trident_server_archive: 'trident-server_{{ trident_server_version }}_amd64.deb'
      trident_server_disturl: '{{ trident_download_dir }}/{{ trident_server_archive }}'
      trident_server_sha256sum: 'a8af27833ada651c9d15dc29d04451250a335ae89a0d2b66bf97a787dced9956'
      trident_server_opts: '--syslog'

      trident_all_version: '{{ trident_version }}'
      trident_all_archive: 'trident_{{ trident_all_version }}_all.deb'
      trident_all_disturl: '{{ trident_download_dir }}/{{ trident_all_archive }}'
      trident_all_sha256sum: '67f57337861098c4e9c9407592c46b04bbc2d64d85f69e8c0b9c18e8d5352ea6' #trident_1.4.5_all.deb

      trident_wikiexport_version: '{{ trident_version }}'
      trident_wikiexport_archive: 'trident-wikiexport_{{ trident_wikiexport_version }}_amd64.deb'
      trident_wikiexport_disturl: '{{ trident_download_dir }}/{{ trident_wikiexport_archive }}'
      trident_wikiexport_sha256sum: '4d2f9d62989594dc5e839546da596094c16c34d129b86e4e323556f1ca1d8805'

      # Pitchfork tracks its own version
      pitchfork_version: '1.9.4'
      pitchfork_archive: 'pitchfork-data_{{ pitchfork_version }}_all.deb'
      pitchfork_disturl: '{{ trident_download_dir }}/{{ pitchfork_archive }}'
      pitchfork_sha256sum: '5b06ae4a20a16a7a5e59981255ba83818f67224b68f6aaec014acf51ca9d1a44'

      # Trident perl tracks its own version
      # TODO(dittrich): trident-perl is private artifact - using our cached copy
      trident_perl_version: '0.1.0'
      trident_perl_archive: 'trident-perl_{{ trident_perl_version }}_amd64.deb'
      trident_perl_disturl: '{{ artifacts_url }}/{{ trident_perl_archive }}'
      trident_perl_sha256sum: '2f120dc75f75f8b2c8e5cdf55a29984e24ee749a75687a10068ed8f353098ffb'

  hosts:
    'yellow':
      # Specific site setting overrides
      trident_site_name: '{{ dims_domain }} Trident Portal'
      trident_site_welcome_text: '{{ dims_domain }} Trident'
      # TODO(dittrich): Prototyping multi-TG settings
      # The primary trust group is the 0th element by convention.
      # Initial user defaults to person running ansible
      # (see roles/trident-core/tasks/main.yml)
      trident_site_trust_groups:
        - name: 'main'
          initial_users:
            - ident: '{{ trident_initial_user_ident }}'
              descr: '{{ trident_initial_user_descr }}'
              email: '{{ trident_initial_user_email }}'
          additional_lists:
            - ident: 'demo'
              descr: 'LOCAL Trident Demos'
            - ident: 'warroom'
              descr: 'LOCAL Trust Group War Room'
            - ident: 'exercise'
              descr: 'LOCAL Trust Group Exercise Comms'
            - ident: 'events'
              descr: 'LOCAL Trust Group Social Events'
          settings:
            descr: 'Main TG'
            pgp_required: 'no'
            has_wiki: 'yes'
            has_file: 'yes'
            has_calendar: 'yes'
            please_vouch: 'yes'
            vouch_adminonly: 'no'
            min_invouch: 0
            min_outvouch: 0
            target_invouch: 0
            max_inactivity: '4320:00:00'
            can_time_out: 'no'
            max_vouchdays: 0
            idle_guard: '168:00:00'
            nom_enabled: 'yes'
            #TODO(dittrich):  trident-configure role can't handle multiple TGs yet.
#       - name: 'admins'
#         initial_users:
#           - ident: 'dims'
#             descr: 'DIMS Mail (no-reply)'
#             email: 'noreply@{{ trident_site_email_domain }}'
#         additional_lists:
#             - ident: 'reports'
#               descr: 'LOCAL System Reports'
#             - ident: 'devops'
#               descr: 'LOCAL DevOps Emails'
#         settings:
#           descr: 'System Administration TG'
#           pgp_required: 'no'
#           has_wiki: 'yes'
#           has_file: 'yes'
#           has_calendar: 'yes'
#           please_vouch: 'yes'
#           vouch_adminonly: 'no'
#           min_invouch: 0
#           min_outvouch: 0
#           target_invouch: 0
#           max_inactivity: '4320:00:00'
#           can_time_out: 'no'
#           max_vouchdays: 0
#           idle_guard: '168:00:00'
#           nom_enabled: 'yes'
    'purple':
      # Specific site setting overrides
      trident_backup_restorefrom: 'latest'
      trident_site_name: '{{ dims_domain }} DevTest Trident Portal'
      trident_site_welcome_text: '{{ dims_domain }} DevTest Trident'
      trident_logo: '{{ files }}/logo/d2-logo.png'
      trident_favicon: '{{ files }}/logo/d2-logo-square.ico'
      # TODO(dittrich): Prototyping multi-TG settings
      # The primary trust group is the 0th element by convention.
      trident_site_trust_groups:
        - name: 'main'
          initial_users:
            - ident: '{{ trident_initial_user_ident }}'
              descr: '{{ trident_initial_user_descr }}'
              email: '{{ trident_initial_user_email }}'
          additional_lists:
            - ident: 'demo'
              descr: 'DevTest Trident Demos'
            - ident: 'warroom'
              descr: 'DevTest Trust Group War Room'
            - ident: 'exercise'
              descr: 'DevTest Trust Group Exercise Comms'
            - ident: 'events'
              descr: 'DevTest Trust Group Social Events'
          settings:
            descr: 'Main TG'
            pgp_required: 'no'
            has_wiki: 'yes'
            has_file: 'yes'
            has_calendar: 'yes'
            please_vouch: 'yes'
            vouch_adminonly: 'no'
            min_invouch: 0
            min_outvouch: 0
            target_invouch: 0
            max_inactivity: '4320:00:00'
            can_time_out: 'no'
            max_vouchdays: 0
            idle_guard: '168:00:00'
            nom_enabled: 'yes'
            #TODO(dittrich):  trident-configure role can't handle multiple TGs yet.
#       - name: 'admins'
#         initial_users:
#           - ident: 'dims'
#             descr: 'DIMS Mail (no-reply)'
#             email: 'noreply@{{ trident_site_email_domain }}'
#         additional_lists:
#             - ident: 'reports'
#               descr: 'LOCAL System Reports'
#             - ident: 'devops'
#               descr: 'LOCAL DevOps Emails'
#         settings:
#           descr: 'System Administration TG'
#           pgp_required: 'no'
#           has_wiki: 'yes'
#           has_file: 'yes'
#           has_calendar: 'yes'
#           please_vouch: 'yes'
#           vouch_adminonly: 'no'
#           min_invouch: 0
#           min_outvouch: 0
#           target_invouch: 0
#           max_inactivity: '4320:00:00'
#           can_time_out: 'no'
#           max_vouchdays: 0
#           idle_guard: '168:00:00'
#           nom_enabled: 'yes'

# vim: ft=ansible :
