---

pycharm_version: '2017.2.3'
pycharm_archive: 'pycharm-community-{{ pycharm_version }}.tar.gz'
pycharm_dist_url: 'https://download.jetbrains.com/python/pycharm-community-{{ pycharm_version }}.tar.gz'
pycharm_sha256_sum: 'e8562938c2ede32a1c1036391942190144cd9f0927bd49b6b3ddf5f7a01c33aa'

# vim: ft=ansible :
