---

# Example playbook from geerlingguy/ansible-role-jenkins
# - hosts: ci_server
#   vars:
#     jenkins_hostname: jenkins.devops.local
#   roles:
#     - ansible-role-jenkins

ci_server:
  vars:
    devops_email_list: 'dave.dittrich@gmail.com'
    git_reposdir: '/opt/git'
    git_authorized_keys: []
    git_mailing_list: '{{ devops_email_list }}'
    git_announce_list: '{{ devops_email_list }}'
    git_envelopesender: 'dims@{{ inventory_hostname }}'
    git_emailprefix: '[Git]'
    git_required_repos:
      - name: 'prisem'
        description: 'PRISEM RPC Utilities'
        upstream: 'git@git.devops.develop:/opt/git/prisem.git'
        post_receive_hooks:
          - logamqp
          - email
          - jenkins
          - jenkinsalldocs
      - name: 'trident-ext-src'
        description: ' package containing all Trident/Pitchfork dependancies.'
        upstream: 'https://github.com/tridentli/trident-ext-src'
        post_receive_hooks:
          - logamqp
          - email
          - jenkins-trident
      - name: 'trident'
        description: 'Trident is a trusted and secure communication platform for enabling better communication between groups of trusted parties https://trident.li'
        upstream: 'https://github.com/tridentli/trident'
        post_receive_hooks:
          - logamqp
          - email
          - jenkins-trident
      - name: 'pitchfork'
        description: 'Golang framework for secure communication platforms.'
        upstream: 'https://github.com/tridentli/pitchfork'
        post_receive_hooks:
          - logamqp
          - email
          - jenkins-trident
    jenkins_repo_url: "deb https://pkg.jenkins.io/debian-stable binary/"
    jenkins_repo_key_url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    jenkins_pkg_url: https://pkg.jenkins.io/debian-stable/binary
    jenkins_version: 2.60.3
    jenkins_package_state: present
    jenkins_connection_delay: 5
    jenkins_connection_retries: 60
    jenkins_home: /var/lib/jenkins
    jenkins_hostname: localhost
    jenkins_port: 8080
    jenkins_ssh_port: 8022
    jenkins_context_path: '/jenkins'
    jenkins_jar_location: "{{ jenkins_home }}/jenkins-cli.jar"
    jenkins_cli: 'ssh -p {{ jenkins_ssh_port }} -l {{ jenkins_admin_username }} {{ jenkins_hostname }}'
    jenkins_labels:
      - '{{ ansible_lsb.codename }}'
      - '{{ ansible_architecture }}'
      - '{{ (ansible_architecture == "x86_64")|ternary("amd64","not_amd64") }}' # For Trident label, until changed
    jenkins_plugins:
      - git
      - git-client
      - git-parameter
      - translation
      - timestamper
      - job-dsl
      - build-name-setter
      - credentials
      - google-login
      - ws-cleanup
      - copyartifact
      - matrix-project
      - matrix-auth
      - ssh-credentials
      - ssh-slaves
      - ssh-agent
      - mailer
      - junit
      - shiningpanda
      - blueocean
      - docker-plugin
      - pam-auth
      - maven-plugin
      - nodejs
      - script-security
      - ldap
      - envinject
      - external-monitor-job
      - antisamy-markup-formatter
      - publish-over-ssh
      - token-macro
      - ant
      - postbuild-task
      - javadoc
      - scm-api
      - parameterized-trigger
    jenkins_url_prefix: "/jenkins"
    jenkins_java_options: "-Djenkins.install.runSetupWizard=false"
    jenkins_plugin_updates_expiration: 86400
    jenkins_plugin_timeout: 60

    jenkins_admin_username: admin
    jenkins_admin_email: 'dave.dittrich@gmail.com'
    jenkins_admin_password: "{{ vault_jenkins_admin_password }}"
    jenkins_admin_password_file: ""
    jenkins_admin_token: ""
    jenkins_admin_token_file: ""

    # For cli_config.yml and its templates
    jenkins_admin_users:
      - 'admin'

    jenkins_authorized_keys: []
    jenkins_process_user: jenkins
    jenkins_process_group: "{{ jenkins_process_user }}"

    jenkins_init_changes:
      - option: "JENKINS_ARGS"
        value: "--prefix={{ jenkins_url_prefix }}"
      - option: "{{ jenkins_java_options_env_var }}"
        value: "{{ jenkins_java_options }}"
    jenkins_job_params:
      'build-rpc-prod':
        repo_url: 'git@git.devops.develop:/opt/git/prisem.git'
        repo_branch: 'master'
      'build-rpc-develop':
        repo_url: 'git@git.devops.develop:/opt/git/prisem.git'
        repo_branch: 'develop'
      'deploy-rpc-prod':
        playbooks_url: 'git@git.devops.develop:/opt/git/ansible-dims-playbooks.git'
        private_url: 'git@git.devops.develop:/opt/git/private-{{ deployment }}.git'
        repo_url: 'git@git.devops.develop:/opt/git/prisem.git'
        repo_branch: 'master'
      'deploy-rpc-develop':
        playbooks_url: 'git@git.devops.develop:/opt/git/ansible-dims-playbooks.git'
        private_url: 'git@git.devops.develop:/opt/git/private-{{ deployment }}.git'
        repo_url: 'git@git.devops.develop:/opt/git/prisem.git'
        repo_branch: 'develop'
      'pitchfork':
        project_url: 'https://github.com/tridentli/pitchfork'
        repo_url: 'https://github.com/tridentli/pitchfork.git'
        repo_branch: 'DEV_1.4.6'
        repo_credentials: ''
      'pitchfork-data':
        project_url: 'https://github.com/tridentli/pitchfork'
        repo_url: 'https://github.com/tridentli/pitchfork.git'
        repo_branch: 'DEV_1.4.6'
        repo_credentials: ''
      'trident':
        project_url: 'https://github.com/tridentli/trident'
        #repo_url: 'https://github.com/tridentli/trident.git'
        repo_url: '/opt/git/trident.git'
        repo_branch: 'DEV_1.4.6'
        #repo_branch: 'develop'
        repo_credentials: ''
      'trident-ext-src':
        project_url: 'https://github.com/tridentli/trident-ext-src'
        repo_url: 'https://github.com/tridentli/trident-ext-src.git'
        repo_branch: 'master'
        repo_credentials: ''
  hosts:
    'orange.devops.local':
      custom_hosts:
        - '10.142.29.98  source.devops.develop'
        - '10.142.29.115  eclipse.devops.develop'
      cronjobs:
        - name: 'source index'
          weekday: '*'
          hour: '*'
          minute: '*'
          user: 'jenkins'
          job: "ls -l {{ nginx_webroot }}/source | egrep -v '^total| index.txt' > {{ nginx_webroot }}/source/index.txt"

# vim: ft=ansible :
