---

# File: roles/postfix/handlers/main.yml

- name: 'Import (dynamic) global handlers'
  import_tasks: "{{ handlers_path }}/restart_services.yml"

- name: restart postfix
  service:
    name: postfix
    state: restarted
  become: yes

- name: reload postfix
  shell: /usr/sbin/postfix reload
  become: yes

- name: rebuild postfix aliases
  shell: /usr/bin/newaliases
  become: yes

- name: rebuild postfix virtual
  shell: /usr/sbin/postmap /etc/postfix/virtual
  become: yes

- name: rebuild postfix transport
  shell: /usr/sbin/postmap /etc/postfix/transport
  become: yes

- name: rebuild postfix generic
  shell: /usr/sbin/postmap /etc/postfix/generic
  become: yes

- name: rebuild postfix access
  shell: /usr/sbin/postmap /etc/postfix/access
  become: yes

- name: rebuild postfix client_access
  shell: /usr/sbin/postmap /etc/postfix/client_access
  become: yes

- name: rebuild postfix helo_access
  shell: /usr/sbin/postmap /etc/postfix/helo_access
  become: yes

- name: rebuild postfix relay_recipients
  shell: /usr/sbin/postmap /etc/postfix/relay_recipients
  become: yes

# vim: vt=ansible:
