---

# file: roles/jenkins2/tasks/main.yml

# Install Jenkins on debian/ubuntu
# https://wiki.jenkins-ci.org/display/JENKINS/Installing+Jenkins+on+Ubuntu

- include: '{{ tasks_path }}/pre_tasks.yml'
  tags: [ jenkins2, packages ]

- name: Install PPA for Java 8
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'
    state: present
    update_cache: yes
  become: yes
  tags: [ jenkins2, packages ]

- name: Ensure Java8 is installed for Jenkins
  apt:
    name: '{{ item }}'
    state: latest
  with_items:
    - openjdk-8-jdk
    - openjdk-8-jre
    - openjdk-8-jre-headless
  become: yes
  tags: [ jenkins2 ]

- name: Ensure Java 7 is purged for Jenkins
  apt:
    name: '{{ item }}'
    state: absent
    purge: yes
  with_items:
    - openjdk-7-jre
    - openjdk-7-jre-headless
    - openjdk-7-jdk
  become: yes
  tags: [ jenkins2 ]

- name: Prevent Java 7 from coming back
  dpkg_selections:
    name: '{{ item }}'
    selection: hold
  with_items:
    - openjdk-7-jre
    - openjdk-7-jre-headless
    - openjdk-7-jdk
  become: yes
  tags: [ jenkins2 ]

# Use the following role for installation

- include_role:
    name: ansible-jenkins2

- name: Ensure (templated) job scripts are present
  template:
    src: '{{ item }}'
    dest: '{{ dims_bin }}/{{ item | basename | regex_replace("\.j2$","") }}'
    owner: '{{ root_user }}'
    group: '{{ root_group }}'
    mode: '{{ mode_0755 }}'
  with_fileglob:
    - "../templates/scripts/*.j2"
  tags: [ jenkins2, scripts ]

- name: Ensure (non-templated) job scripts are present
  copy:
    src: '{{ item }}'
    dest: '{{ dims_bin }}/{{ item | basename | regex_replace("\.sh$","") }}'
    owner: '{{ root_user }}'
    group: '{{ root_group }}'
    mode: '{{ mode_0755 }}'
  with_fileglob:
    - "../files/scripts/*.sh"
  tags: [ jenkins2, scripts ]

- name: Make defined bats tests present
  include: "{{ tasks_path }}/bats-tests.yml"
  ignore_errors: yes
  tags: [ jenkins2, tests ]

- include: "{{ tasks_path }}/post_tasks.yml"
  tags: [ jenkins2, packages ]

# vim: ft=ansible :
