---

# File: roles/jenkins2/tasks/main.yml

# The role 'geerlingguy/ansible-role-jenkins' is being used to
# install Jenkins. It requires Java8, so the role 'java8' from
# this repo is required as a pre-requisite. This role is then used
# to configure Jenkins jobs install bats test scripts that
# conform with DIMS project requirements.
#
# This would be better done with a single role that uses
# a mechanism like "include_role", but as of Ansible 2.3.0.0,
# there are still bugs that prevent handlers from executing
# properly that make this not possible.

- include: '{{ tasks_path }}/pre_tasks.yml'
  tags: [ jenkins2, packages ]

## We want to pin the version of Jenkins for stability
## reasons.

- name: Hold updates of jenkins package
  dpkg_selections:
    name: jenkins
    selection: hold
  become: yes
  tags: [ jenkins2, packages ]

- name: Ensure ansible user is in jenkins group
  user:
    name: ansible
    append: yes
    groups: jenkins
  become: yes
  when: "groups['ci-server'] is defined and inventory_hostname in groups['ci-server']"
  tags: [ jenkins2 ]

# Install bats tests first so we can use them to validate
# installation of Java and Jenkins.

- name: Make defined bats tests present
  include: "{{ tasks_path }}/bats-tests.yml"
  ignore_errors: yes
  tags: [ jenkins2, tests ]

- name: Run system test for Java8 installation
  command: "{{ dims_bin }}/test.runner --tap --level system --match 'java8-install'"
  environment:
    DIMS: '{{ dims }}'
    PATH: '{{ dims_bin }}:{{ ansible_env.PATH }}'
  tags: [ jenkins2 ]

- name: Make Jenkins nginx front end present
  template:
    src: '{{ item }}'
    dest: /etc/nginx/sites-available/jenkins
    owner: '{{ root_user }}'
    group: '{{ root_group }}'
    mode: '{{ mode_0644 }}'
  with_first_found:
    - files:
       - '{{ nginx_confd_jenkins }}'
       - jenkins.{{ inventory_hostname }}.j2
       - jenkins.category-{{ category }}.j2
       - jenkins.deployment-{{ deployment }}.j2
       - jenkins.j2
      paths:
       - '{{ dims_private }}/roles/{{ role_name }}/templates/nginx/'
       - nginx/
  become: yes
  notify: restart nginx
  tags: [ jenkins2, config ]

- name: Create symlink to enable site
  file:
    src: '/etc/nginx/sites-available/{{ item }}'
    dest: '/etc/nginx/sites-enabled/{{ item }}'
    state: link
  with_items:
    - jenkins
  notify: restart nginx
  tags: [ jenkins2, config ]

- name: Ensure members of jenkins group can read secrets
  file:
    path: '{{ jenkins_home }}/secrets'
    state: directory
    owner: '{{ jenkins_process_user }}'
    group: '{{ jenkins_process_user }}'
    mode: '{{ mode_0770 }}'
  become: yes
  notify: restart nginx
  tags: [ jenkins2, config ]

- name: Ensure admin password is absent
  file:
    path: '{{ jenkins_home }}/secrets/AdminPassword'
    state: absent
  become: yes
  tags: [ jenkins2, config ]

- name: Ensure admin password is available for jenkins-cli
  lineinfile:
    line: '{{ jenkins_admin_password }}'
    path: '{{ jenkins_home }}/secrets/AdminPassword'
    backup: yes
    create: yes
    state: present
    owner: '{{ jenkins_process_user }}'
    group: '{{ jenkins_process_user }}'
    mode: "{{ mode_0640 }}"
  become: yes
  tags: [ jenkins2, config ]

- name: Make artifacts (source) directory present
  file:
    path: '{{ dims }}/source'
    state: directory
    owner: '{{ dims_user }}'
    group: www-data
    mode: '{{ mode_0775 }}'
  become: yes
  notify: restart nginx
  tags: [ jenkins2, config ]

- name: Bootstrap artifacts from ~ansible/sources
  shell: >
    cp /home/ansible/sources/* {{ dims }}/source &&
    chown {{ dims_user }}:www-data {{ dims }}/source/* &&
    chmod 644 {{ dims }}/source/*
  become: yes
  when: inventory_hostname in groups['ci-server']
  ignore_errors: yes
  tags: [ jenkins2, config ]

- name: Ensure jenkins user is in www-data group
  user:
    name: jenkins
    append: yes
    groups: www-data
  become: yes
  notify: restart nginx
  tags: [ jenkins2, config ]

- name: Ensure (templated) job scripts are present
  template:
    src: '{{ item }}'
    dest: '{{ dims_bin }}/{{ item | basename | regex_replace("\.j2$","") }}'
    owner: '{{ root_user }}'
    group: '{{ root_group }}'
    mode: '{{ mode_0755 }}'
  with_fileglob:
    - "../templates/scripts/*.j2"
  tags: [ jenkins2, scripts ]

- name: Ensure (non-templated) job scripts are present
  copy:
    src: '{{ item }}'
    dest: '{{ dims_bin }}/{{ item | basename | regex_replace("\.sh$","") }}'
    owner: '{{ root_user }}'
    group: '{{ root_group }}'
    mode: '{{ mode_0755 }}'
  with_fileglob:
    - "../files/scripts/*.sh"
  tags: [ jenkins2, scripts ]

- include: "{{ tasks_path }}/post_tasks.yml"
  tags: [ jenkins2, packages ]

# vim: ft=ansible :
