---

# File: playbooks/groups/dns.yml

# create a new dns server

- import_tasks: "/opt/dims/ansible/playbooks/include/virt-create.yml myhosts=dns"

- name: make the box be real
  hosts: dns
  user: root
  gather_facts: True

  vars_files: 
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  roles:
  - base
  - hosts
  - sudo
  - { role: openvpn/client, when: datacenter != "phx2" }
  - dns

  tasks:
  - import_tasks: "{{ tasks_path }}/aptrepos.yml"
  - import_tasks: "{{ tasks_path }}/yumrepos.yml"
#  - import_tasks: "{{ tasks_path }}/2fa_client.yml"
  - import_tasks: "{{ tasks_path }}/motd.yml"

  handlers:
  - import_tasks: "{{ handlers_path }}/restart_services.yml"
