---

# File: playbooks/groups/packages.yml

# create a new packages server
# NOTE: should be used with --limit most of the time
# NOTE: make sure there is room/space for this server on the vmhost
# NOTE: most of these vars_path come from group_vars/packages* or from hostvars

- include: "/opt/dims//ansible/playbooks/include/virt-create.yml myhosts=packages:packages-stg"

- name: make the box be real
  hosts: packages;packages-stg
  user: root
  gather_facts: True

  vars_files:
   - /opt/dims/ansible/vars/global.yml
   - "/opt/dims/private/ansible/vars.yml"
   - /opt/dims/ansible/vars/{{ ansible_distribution }}.yml

  roles:
  - base
  - hosts
  - sudo
  - { role: openvpn/client,
      when: env != "staging" }

  tasks:
  - include: "{{ tasks }}/aptrepos.yml"
  - include: "{{ tasks }}/yumrepos.yml"
#  - include: "{{ tasks }}/2fa_client.yml"
  - include: "{{ tasks }}/motd.yml"

  handlers:
  - include: "{{ handlers }}/restart_services.yml"

