---

# File: roles/consul/tasks/main.yml

# Can override defaults for the ansible vars in start_consul.sh script
# when executing ansible-playbook

- name: Kill any current running instance and remove
  shell: "docker stop consul && docker rm consul"
  sudo: yes
  ignore_errors: yes
#  docker: 
#    name: consul
#    image: consul
#    state: absent

#- name: start Consul agent in Docker container
#  docker:
#    name: consul
#    image: consul
#    state: started
#    command: "agent -bind={{ consulInetInterface }} -retry-join={{ consulRetryJoin }}"
#  when: consulMode == "client"

- name: Copy script template to target
  template: src=start_consul.sh.j2 dest=/tmp/start_consul.sh mode=774

- name: Start new instance of consul container
  shell: sh /tmp/start_consul.sh
  sudo: yes

#- include: post_tasks.yml

