---

# file: roles/consul/tasks/main.yml

# Tasks for setting up a Consul agent/peer.

- include: "{{ tasks }}/pre_tasks.yml"
  tags: [ consul, config, packages ]

- include: tasks/debian-main.yml
  when: ansible_os_family == "Debian"
  tags: [ consul, config, packages ]

- include: tasks/coreos-main.yml
  when: ansible_os_family == "Container Linux by CoreOS"
  tags: [ consul, config, packages ]

- name: Make defined bats tests present
  include: "{{ tasks }}/bats-tests.yml"
  tags: [ consul, tests ]

- include: "{{ tasks }}/post_tasks.yml"
  tags: [ consul, config, packages ]

# vim: ft=ansible :
