---

# file: roles/consul/tasks/main.yml

# Tasks for setting up a Consul agent/peer.

- import_tasks: "{{ tasks_path }}/pre_tasks.yml"
  tags: [ consul, config, tests, packages ]

- debug:
    msg: "{{ inventory_hostname }} is not in groups.consul"
  when: not (groups.consul is defined and
             inventory_hostname in groups.consul)
  tags: [ consul, config, tests, packages ]

- import_tasks: tasks/debian-main.yml
  when: ansible_os_family == "Debian" and
        groups.consul is defined and
        inventory_hostname in groups.consul
  tags: [ consul, config, packages ]

- import_tasks: tasks/coreos-main.yml
  when: ansible_os_family == "Container Linux by CoreOS" and
        groups.consul is defined and
        inventory_hostname in groups.consul
  tags: [ consul, config, packages ]

- import_tasks: "{{ tasks_path }}/post_tasks.yml"
  tags: [ consul, config, tests, packages ]

# vim: ft=ansible :
