include $(DIMS)/etc/Makefile.dims.global
include $(GIT)/dims-dockerfiles/dockerfiles/Makefile.container

#HELP setup - load pre-requisites needed for building Docker image
setup:
	make -f GNUmakefile shflags bats
