---

# File: roles/ansible-server/tasks/main.yml

# Set up system to serve as an Ansible control host.

- name: Define ansible_dims_playbooks_repo
  set_fact:
    ansible_dims_playbooks_repo: '{{ _ansible_dims_playbooks_repo }}'
  when: ansible_dims_playbooks_repo is not defined
  tags: [ ansible-server ]

- name: Define ansible_dims_playbooks_version
  set_fact:
    ansible_dims_playbooks_version: '{{ _ansible_dims_playbooks_version }}'
  when: ansible_dims_playbooks_version is not defined
  tags: [ ansible-server ]

- name: Define dims_ansible_imported_roles
  set_fact:
    dims_ansible_imported_roles: '{{ _dims_ansible_imported_roles }}'
  when: dims_ansible_imported_roles is not defined
  tags: [ ansible-server ]

- include: '{{ tasks_path }}/pre_tasks.yml'
  tags: [ ansible-server ]

- name: Make sure directory exists for ansible configurations
  file:
    path: /etc/ansible
    state: directory
    owner: '{{ root_user }}'
    group: '{{ root_group }}'
    mode: 0o775
  become: yes
  tags: [ ansible-server, config ]

- name: Make sure directory exists for ansible fact caching
  file:
    path: '{{ dims_data }}/facts.d/'
    state: directory
    owner: '{{ dims_user }}'
    group: '{{ dims_group }}'
    mode: 0o770
  become: yes
  tags: [ ansible-server, config ]

  # This is the default configuration file for the entire system. It cannot
  # reference a user-customizable environment variable that is not set in
  # the environment of other users who would be invoking Ansible command
  # line programs. Keep this in mind when setting variables for Jinja
  # templating in the source files in the ansible.cfg/ directory.

- name: Generate default ansible config
  template:
    src: '{{ item }}'
    dest: /etc/ansible/ansible.cfg
    owner: '{{ root_user }}'
    group: '{{ root_group }}'
    mode: 0o644
  with_first_found:
    - files:
        - '{{ ansible_config }}'
        - ansible.cfg.{{ inventory_hostname }}.j2
        - ansible.cfg.category-{{ category }}.j2
        - ansible.cfg.deployment-{{ deployment }}.j2
        - ansible.cfg.j2
      paths:
        - '{{ dims_private }}/roles/{{ role_name }}/templates/ansible.cfg/'
        - ansible.cfg/
  become: yes
  tags: [ ansible-server, config ]

  # This only works for INI-style inventory files. The configuration file
  # above may reference a directory, a dynamic inventory script, and/or a
  # YAML inventory file (or combination thereof). Keep that in mind when
  # altering or configuring this default file.

- name: Generate default ansible hosts file
  template:
    src: '{{ item }}'
    dest: /etc/ansible/hosts
    owner: '{{ root_user }}'
    group: '{{ root_group }}'
    mode: 0o644
  with_first_found:
    - files:
        - '{{ ansible_hosts_file }}'
        - hosts.{{ inventory_hostname }}.j2
        - hosts.category-{{ category }}.j2
        - hosts.deployment-{{ deployment }}.j2
        - hosts.j2
      paths:
        - '{{ dims_private }}/roles/{{ role_name }}/templates/ansible-hosts/'
        - ansible-hosts/
  become: yes
  tags: [ ansible-server, config ]

- name: Create imported plugins/roles directory
  file:
    path: '{{ item }}'
    owner: '{{ dims_user }}'
    group: '{{ dims_group }}'
    state: directory
    mode: 0o775
  with_items:
    - '{{ imported_plugins }}'
    - '{{ imported_roles }}'
  become: yes
  tags: [ ansible-server, config ]

- name: Ensure imported roles present
  git:
    repo: '{{ item }}'
    dest: '{{ imported_roles }}/{{ item | basename | regex_replace(".git", "") }}'
    force: true
  become: yes
  with_items:
    - '{{ dims_ansible_imported_roles }}'
  when: dims_ansible_imported_roles is defined
  tags: [ ansible-server ]

- name: Ensure ansible-dims-playbooks present
  git:
    repo: 'https://github.com/uw-dims/ansible-dims-playbooks.git'
    dest: '{{ dims_git }}/ansible-dims-playbooks'
    version: '{{ ansible_dims_playbooks_version }}'
    update: yes
    force: yes
  tags: [ ansible-server ]

- name: Define install_ssh_keypair
  set_fact:
    install_ssh_keypair: false
  when: install_ssh_keypair is not defined
  tags: [ ansible-server ]

- name: Define variable with ansible private key
  set_fact:
    _private_key_file: '{{ lookup("dims_function", "get_ssh_private_key_file {{ ansible_user }}") }}'
  tags: [ ansible-server ]

- fail: msg="Could not look up \"dims_function get_ssh_private_key_file ansible\""
  when: _private_key_file is not defined or _private_key_file == ''
  tags: [ ansible-server ]

- name: Ensure ansible SSH key pair is present
  copy:
    src: '{{ item }}'
    dest: '/home/{{ ansible_user }}/.ssh/{{ item|basename }}'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: 0o600
  with_items:
    - '{{ _private_key_file }}'
    - '{{ _private_key_file }}.pub'
  when: install_ssh_keypair is defined and install_ssh_keypair|bool
  become: yes
  tags: [ ansible-server ]

- include: '{{ tasks_path }}/post_tasks.yml'
  tags: [ ansible-server ]

# vim: ft=ansible :
