---

# File: roles/java8/tasks/main.yml

# Jenkins 2 requires Java8. This simple role ensures that
# Java8 is present and that Java 7 is not.

- import_tasks: '{{ tasks_path }}/pre_tasks.yml'
  tags: [ java8, packages ]

- name: Ensure PPA for Java 8 is present
  apt_repository:
    repo: '{{ java8_apt_repo }}'
    state: present
    update_cache: yes
  become: yes
  tags: [ java8, packages ]

- name: Ensure Java8 is installed
  apt:
    name: '{{ item }}'
    state: latest
    default_release: '{{ java8_default_release }}'
  with_items:
    - '{{ java8_packages }}'
  become: yes
  tags: [ java8, packages ]

- name: Ensure Java 7 is purged
  apt:
    name: '{{ item }}'
    state: absent
    purge: yes
  with_items:
    - '{{ java7_packages }}'
  become: yes
  tags: [ java8, packages ]

- name: Hold updates of Java 7 packages
  dpkg_selections:
    name: '{{ item }}'
    selection: hold
  with_items:
    - '{{ java7_packages }}'
  become: yes
  tags: [ java8, packages ]

- import_tasks: "{{ tasks_path }}/post_tasks.yml"
  tags: [ java8, packages ]

# vim: ft=ansible :
