---

- Variable: jenkins_admin_password
  Type: password

- Variable: devops_email_list
  Type: string
  Prompt: 'Email list identifier for CI/CD services'

- Variable: jenkins_admin_email
  Type: string
  Prompt: 'Email address for Jenkins admin email'

- Variable: git_authorized_keys
  Type: string
  Prompt: 'Authorized SSH key for private packages'

# vim: ft=ansible :
