---

# Virtualbox uses a more complicated versioning mechanism than
# other programs, requiring more variables to build the
# distribution artifact URL. :(
# http://download.virtualbox.org/virtualbox/N.N.NN/virtualbox-N.N_N.N.NN-NNNNNN~Ubuntu~trusty_amd64.deb
# https://www.virtualbox.org/wiki/Linux_Downloads

virtualbox_major_version: '5.1'
virtualbox_asc_fingerprint: '7B0F AB3A 13B9 0743 5925  D9C9 5442 2A4B 98AB 5139'
virtualbox_2016asc_fingerprint: 'B9F8 D658 297A F3EF C18D  5CDF A2F6 83C5 2980 AECF'
virtualbox_version: '{{ virtualbox_major_version }}.28'
virtualbox_release: '117968'
virtualbox_release_version: '{{ virtualbox_version }}-{{ virtualbox_release }}'
virtualbox_deb_sha256sum: '78e9a41e91129b4cb687ead58d05fc99d98961b73bb1372c3654b4ed635a1c1a'
virtualbox_artifact: 'virtualbox-{{ virtualbox_major_version }}_{{ virtualbox_release_version }}~Ubuntu~trusty_amd64.deb'
virtualbox_dist_url: 'http://download.virtualbox.org/virtualbox/{{ virtualbox_version }}'


# vim: ft=ansible :
