---

# File: roles/docker/defaults/main.yml

_docker_apt_key_url: 'https://download.docker.com/linux/{{ ansible_distribution|lowercase }}/gpg'
_docker_apt_key_id: '9DC858229FC7DD38854AE2D88D81803C0EBFCD88'
_docker_repo_host: 'download.docker.com'
_docker_ce_pool: 'stable'
_docker_ce_version: '18.06.1~ce~3-0'
_docker_compose_version: '1.22.0'
# Don't default to installing docker-machine

# vim: ft=ansible :
