---

all:
  vars:
    dist_tag: "u'{{ ansible_distribution_version }}'"
    os_version: '?'
    ansible_user: 'ansible'
    ansible_ssh_private_key_file: "{{ lookup('dims_function', 'get_ssh_private_key_file {{ ansible_user }} {{ dims_private }}') }}"
    category: 'devops'
    deployment: 'local'
    dims_domain: '{{ category }}.{{ deployment }}'
    playbooks_root: "{{ lookup('env', 'PBR') }}"
    dims_private: "{{ playbooks_root }}"
    artifacts_url: 'http://source.{{ dims_domain }}/source'
  hosts:
    'black.devops.local':
    'node01.devops.local':
    'node02.devops.local':
    'node03.devops.local':
    'orange.devops.local':
    'purple.devops.local':
    'red.devops.local':
    'gray.devops.local':
    'yellow.devops.local':
  children:
    production:
      hosts:
        'red.devops.local':
        'node01.devops.local':
        'node02.devops.local':
        'node03.devops.local':
        'yellow.devops.local':
        'orange.devops.local':
    development:
      hosts:
        'black.devops.local':
        'purple.devops.local':
    devtest:
      hosts:
        'red.devops.local':
        'orange.devops.local':
        'purple.devops.local':
        'blue.devops.local':
    coreos:
      vars:
        ssl_certs_dir: '?'
        ssl_key_dir: '?'
      hosts:
        'node01.devops.local':
          os_version: '?'
        'node02.devops.local':
          os_version: '?'
        'node03.devops.local':
          os_version: '?'
    ubuntu:
      vars:
        ssl_certs_dir: '/etc/ssl/certs'
        ssl_key_dir: '/etc/ssl/private'
        packages_install:
          - 'apt-transport-https'
          - 'bash-completion'
          - 'ca-certificates'
          - 'chrony'
          - 'chrony'
          - 'cpanminus'
          - 'curl'
          - 'dconf-tools'
          - 'default-jdk'
          - 'git-core'
          - 'gitk'
          - 'gnupg2'
          - 'htop'
          - 'hunspell'
          - 'ifstat'
          - 'iptables-persistent'
          - 'make'
          - 'myrepos'
          - 'netcat'
          - 'nfs-common'
          - 'nfs-kernel-server'
          - 'ntpdate'
          - 'openssh-server'
          - 'patch'
          - 'perl'
          - 'postfix'
          - 'python'
          - 'python-apt'
          - 'remake'
          - 'rsync'
          - 'rsyslog'
          - 'smartmontools'
          - 'software-properties-common'
          - 'sshfs'
          - 'sshpass'
          - 'strace'
          - 'tree'
          - 'unzip'
          - 'vim'
          - 'xml-twig-tools'
          - 'xsltproc'
        packages_remove:
          - 'modemmanager'
          - 'resolvconf'
          - 'sendmail'
        services_disabled: [ ]
        services_enabled:
          - 'auditd'
        root_user: 'root'
        root_group: 'root'
      hosts:
        'black.devops.local':
          os_version: '14.04.5'
    debian:
      vars:
        ssl_certs_dir: '/etc/ssl/certs'
        ssl_key_dir: '/etc/ssl/private'
        packages_install:
          - 'apt-transport-https'
          - 'bash-completion'
          - 'ca-certificates'
          - 'chrony'
          - 'cpanminus'
          - 'curl'
          - 'dconf-tools'
          - 'debian-archive-keyring'
          - 'git-core'
          - 'gitk'
          - 'gnupg2'
          - 'htop'
          - 'hunspell'
          - 'ifstat'
          - 'iptables-persistent'
          - 'make'
          - 'myrepos'
          - 'netcat'
          - 'nfs-common'
          - 'ntpdate'
          - 'openssh-server'
          - 'patch'
          - 'perl'
          - 'postfix'
          - 'python'
          - 'python-apt'
          - 'remake'
          - 'rsync'
          - 'rsyslog'
          - 'smartmontools'
          - 'software-properties-common'
          - 'sshfs'
          - 'strace'
          - 'tree'
          - 'unzip'
          - 'vim'
          - 'xml-twig-tools'
          - 'xsltproc'
        packages_remove:
          - 'modemmanager'
          - 'resolvconf'
          - 'sendmail'
        services_disabled: [ ]
        services_enabled:
          - 'auditd'
      hosts:
        'red.devops.local':
          os_version: '8.5.0'
        'orange.devops.local':
          os_version: '8.5.0'
        'gray.devops.local':
          os_version: '8.5.0'
        'green.devops.local':
          os_version: '7.11.0'
        'purple.devops.local':
          os_version: '8.5.0'
        'yellow.devops.local':
          os_version: '8.5.0'
    darwin:
      vars:
        syslog_user: 'root'
        root_user: 'root'
        root_group: 'wheel'
    centos:
      vars:
        ssl_certs_dir: '/etc/pki/ca-trust/source/anchors/'
        ssl_key_dir: '/etc/pki/tls/private'
        syslog_user: 'root'
        root_user: 'root'
        root_group: 'root'
        packages_install:
          - 'bash-completion'
          - 'ca-certificates'
          - 'chrony'
          - 'curl'
          - 'git-core'
          - 'gitk'
          - 'gnupg2'
          - 'htop'
          - 'hunspell'
          - 'libxslt'
          - 'make'
          - 'nc'
          - 'ntpdate'
          - 'openssh-server'
          - 'patch'
          - 'perl'
          - 'perl-XML-Twig'
          - 'postfix'
          - 'python'
          - 'rsync'
          - 'rsyslog'
          - 'sshfs'
          - 'strace'
          - 'tree'
          - 'unzip'
          - 'vim'
        packages_remove:
          - 'firewalld'
          - 'modemmanager'
          - 'resolvconf'
          - 'sendmail'
        services_disabled: []
        services_enabled:
          - 'auditd'
      hosts:
        'blue.devops.local':

# vim: ft=ansible:
