---

# File: tasks/bats-tests.yml

# This task file handles a multi-level test subdirectory
# hierarchy that supports multiple test levels and test
# classes as defined in the DIMS Test Plan:
#
# http://dims-tp.readthedocs.io/en/latest/testidentification.html#test-levels
#
# Examples of projects that similarly split out types of
# tests, in a manner like that implemented in this task
# playbook, are:
#
# https://github.com/docker/machine/tree/master/test
# https://github.com/docker/swarm/tree/master/test

# The Jinja templates don't seem to be easily split over
# multiple lines, so they are left as big long lines
# despite possible readability problems.

- name: Set fact with list of test directories
  set_fact:
    test_directories="{{ lookup('pipe','cd {{ playbooks_root }}/roles/{{ role_name }}/templates/tests && find * -type d').split() }}"

- name: Make subdirectories for test categories present
  file:
    state: directory
    dest: '{{ dims_tests }}/{{ item }}'
    owner: '{{ dims_user }}'
    group: '{{ dims_group }}'
    mode: '{{ mode_0755 }}'
  with_items: '{{ test_directories }}'
  when: test_directories is defined

# This playbook assumes that all Bats helpers and
# bash scripts are kept at the top level of the
# tests directory.  Links to these files will be
# created at each subordinate level to allow simpler
# loading of helpers in a consistent manner.

- name: Make bats functions present
  template:
    src: '{{ item }}'
    dest: '{{ dims_tests }}/{{ item | basename | regex_replace("\.j2","") }}'
    owner: '{{ dims_user }}'
    group: '{{ dims_group }}'
    mode: '{{ mode_0755 }}'
  with_fileglob:
   - ../templates/tests/*.bash.j2

- name: Set fact with list of .bash scripts in top level tests directory
  shell: "cd {{ dims_tests }} && find * -maxdepth 1 -type f -name '*.bash'"
  register: scripts

- name: Make links to helper functions present
  file:
    state: link
    src: '{{ dims_tests }}/{{ item[1] }}'
    path: '{{ dims_tests }}/{{ item[0] }}/{{ item[1] }}'
  with_nested:
    - '{{ test_directories }}'
    - '{{ scripts.stdout_lines }}'
  when: test_directories is defined and scripts.stdout_lines is defined

# The Jinja templates don't seem to be easily split over
# multiple lines, so they are left as big long lines
# despite possible readability problems.

- name: Identify bats test templates
  set_fact:
    bats_test_templates="{{ lookup('pipe','cd {{ playbooks_root }}/roles/{{ role_name }}/templates/tests 2>/dev/null && find . -type f -name \"*.bats.j2\"').split() }}"
  ignore_errors: yes

- name: Make defined bats tests present
  template:
    src: ../templates/tests/{{ item }}
    dest: '{{ dims_tests }}/{{ item | dirname }}/{{ item | basename | regex_replace("\.j2","") }}'
    owner: '{{ dims_user }}'
    group: '{{ dims_group }}'
    mode: '{{ mode_0755 }}'
  with_items: '{{ bats_test_templates }}'
  ignore_errors: yes
  when: bats_test_templates is defined

# vim: ft=ansible :
