---

# File: tasks/configure-trident-password.yml

- name: Load deployment secrets
  include_vars: "{{ playbooks_root }}/inventory/{{ deployment }}/group_vars/{{ deployment }}-vault.yml"
  no_log: '{{ nolog }}'
  when: ansible_lsb.codename == "jessie"

- name: Ensure administator is logged in
  shell: >
    tcli system login trident {{ tridentSysAdminPass }}
  register: tcli_login
  no_log: '{{ nolog }}'
  when: ansible_lsb.codename == "jessie"

- fail: "Failed to log in via trident: {{ tcli_login.stdout }}"
  when: ansible_lsb.codename == "jessie"
        and tcli_login.stdout != "Login successful"

- name: Ensure administrator logged in with sysadmin rights
  shell: >
    tcli system swapadmin
  register: tcli_swapadmin
  no_log: '{{ nolog }}'
  when: ansible_lsb.codename == "jessie"
        and tcli_login.stdout == "Login successful"

- fail: "Failed to obtain sysadmin rights: {{ tcli_swapadmin.stdout }}"
  when: ansible_lsb.codename == "jessie"
        and tcli_swapadmin.stdout != "Now a SysAdmin user"

- name: Ensure global admin accounts have default passwords
  shell: >
    tcli user password set portal {{ item.ident }} {{ tridentSysAdminPass }}
  with_items: "{{ trident.admins }}"
  no_log: "{{ nolog }}"
  when: ansible_lsb.codename == "jessie"
        and tcli_login.stdout == "Login successful"
        and tcli_swapadmin.stdout == "Now a SysAdmin user"
        and admins
  ignore_errors: yes

- name: Ensure primary_tg member accounts have default passwords
  shell: >
    tcli user password set portal {{ item.ident }} {{ tridentSysAdminPass }}
  with_items: "{{ trident.primary_tg.members }}"
  no_log: "{{ nolog }}"
  when: ansible_lsb.codename == "jessie"
        and tcli_login.stdout == "Login successful"
        and tcli_swapadmin.stdout == "Now a SysAdmin user"
        and members
  ignore_errors: yes

# EOF
