---

# File: tasks/configure-trident-password.yml

- name: Load deployment secrets
  include_vars: "{{ dims_private }}/group_vars/vault.yml"
  no_log: '{{ no_log }}'
  when: ansible_lsb.codename == "jessie"

- name: Ensure administator is logged in
  shell: >
    tcli system login trident {{ trident_sysadmin_pass }}
  register: tcli_login
  no_log: '{{ no_log }}'
  when: ansible_lsb.codename == "jessie"

- fail: msg="Failed to log in via trident: {{ tcli_login.stdout }}"
  when: ansible_lsb.codename == "jessie"
        and tcli_login.stdout != "Login successful"

- name: Ensure administrator logged in with sysadmin rights
  shell: >
    tcli system swapadmin
  register: tcli_swapadmin
  no_log: '{{ no_log }}'
  when: ansible_lsb.codename == "jessie"
        and tcli_login.stdout == "Login successful"

- fail: msg="Failed to obtain sysadmin rights: {{ tcli_swapadmin.stdout }}"
  when: ansible_lsb.codename == "jessie"
        and tcli_swapadmin.stdout != "Now a SysAdmin user"

- name: Ensure global admin accounts have default passwords
  shell: >
    tcli user password set portal {{ item.ident }} {{ trident_sysadmin_pass }}
  with_items: "{{ trident_site_admins }}"
  no_log: "{{ no_log }}"
  when: ansible_lsb.codename == "jessie"
        and tcli_login.stdout == "Login successful"
        and tcli_swapadmin.stdout == "Now a SysAdmin user"
        and admins
  ignore_errors: yes

- name: Ensure primary TG member accounts have default passwords
  shell: >
    tcli user password set portal {{ item.ident }} {{ trident_sysadmin_pass }}
  with_items: "{{ trident_site_trust_groups.0.initial_users }}"
  no_log: "{{ no_log }}"
  when: ansible_lsb.codename == "jessie"
        and tcli_login.stdout == "Login successful"
        and tcli_swapadmin.stdout == "Now a SysAdmin user"
        and members
  ignore_errors: yes

# EOF
