---

# File: tasks/debug-dump-vars.yml

- debug: verbosity=5 var=inventory_dir
  run_once: true

- debug: verbosity=5 var=play_hosts
  run_once: true

- debug: verbosity=5 var=environment
  run_once: true

- debug: verbosity=5 var=hostvars[item]
  with_items: play_hosts
  run_once: true

# vim: ft=ansible :
