---

# File: tasks/dnsmasq.yml

# NOTE: Ubuntu 14.04 does not support dnsmasq anymore in a workable
# way. There is an incompatible pre-requisite with init-system-helpers
# that cannot be resolved using Ubuntu packages or backports.
# Instead, we're installing from source everywhere to stay
# consistent in version being used to avoid breaking things.
# (See also comments in roles/dns/tasks/main.yml)

- name: Only "update_cache=yes" if >3600s since last update
  apt: update_cache=yes cache_valid_time=3600
  become: yes
  when: ansible_os_family == "Debian"

- name: Make full dnsmasq present (Debian, Trusty)
  apt: name=dnsmasq=2.68-1ubuntu0.1 state=present force=yes
  become: yes
  when: ansible_os_family == "Debian" and ansible_lsb.codename == "trusty"

- name: Make full dnsmasq package present (Debian, not Trusty)
  apt: name=dnsmasq state=present force=yes
  become: yes
  when: ansible_os_family == "Debian" and ansible_lsb.codename != "trusty"

- name: Make dbus-1 development libraries present
  apt: name=libdbus-1-dev state=present force=yes
  become: yes

- name: Download dnsmasq source
  get_url:
    url: "{{ dnsmasq_dist_url }}"
    sha256sum: "{{ dnsmasq_sha256_sum }}"
    dest: "{{ dims_deploy }}/{{ dnsmasq_archive }}"
    validate_certs: false
  become: yes
  when: ansible_os_family == "Debian" and ansible_lsb.codename == "trusty"

- name: Unpack dnsmasq archive file
  unarchive:
    src:  "{{ dims_deploy }}/{{ dnsmasq_archive }}"
    dest: "{{ dims_deploy }}/"
    copy: no
  become: yes
  when: ansible_os_family == "Debian" and ansible_lsb.codename == "trusty"

- name: Compile and install dnsmasq
  shell: >
    cd {{ dims_deploy }}/dnsmasq-{{ dnsmasq_version }} &&
    make COPTS="-DHAVE_DBUS" PREFIX=/usr install
  become: yes
  when: ansible_os_family == "Debian" and ansible_lsb.codename == "trusty"

- name: Clean up dnsmasq build artifacts
  file: "state=absent path={{ item }}"
  with_items:
    - "{{ dims_deploy }}/dnsmasq-{{ dnsmasq_version }}"
    - "{{ dims_deploy }}/{{ dnsmasq_archive }}"
  become: yes
  when: ansible_os_family == "Debian" and ansible_lsb.codename == "trusty"

