---

# File: tasks/hostname.yml
#
# Ensure hostname is set to FQDN, domain name is set.
#
- name: Assert dims_fqdn is defined and not null
  assert:
    that:
      - dims_fqdn is defined
      - dims_fqdn != ''

- name: Define dims_fqdn
  set_fact:
    dims_fqdn: '{{ inventory_hostname }}.{{ dims_domain }}'
  when: dims_fqdn is not defined

- debug: msg=System "{{ inventory_hostname }} ({{ dims_fqdn }})"
  when: verbose

- name: Make /etc/hostname present
  shell: 'echo {{ dims_fqdn }} > /etc/hostname'
  become: yes
  when: ansible_os_family != "MacOSX"

- name: Set hostname (runtime) (Debian)
  shell: 'hostname -b -F /etc/hostname'
  become: yes
  when: ansible_distribution == "Debian"

- name: Ensure kernel uses FQDN hostname (Debian)
  sysctl:
    name: kernel.hostname
    value: '{{ dims_fqdn }}'
    sysctl_set: yes
    state: present
    reload: yes
  become: yes
  when: ansible_distribution == "Debian"

- name: Set hostname (runtime) (Ubuntu, CoreOS)
  shell: 'hostname {{ dims_fqdn }}'
  become: yes
  when: ansible_distribution == "Ubuntu" or ansible_os_family == "Container Linux by CoreOS"

- name: Set domainname (MacOSX)
  lineinfile:
    dest=/etc/defaultdomain
    regexp='^.*$'
    line={{ dims_domain }}
    owner={{ root_user }}
    group={{ root_group }}
    mode=0o644
  become: yes
  when: ansible_os_family == "MacOSX"

# vim: ft=ansible :
