---

# File: tasks/install-certbot-certs.yml

- name: Define certbot_sitename
  set_fact:
    certbot_sitename: '{{ tridentFQDN }}' # For now, use this variable
  when: certbot_sitename is not defined

- name: Define certbot_adminemail
  set_fact:
    certbot_adminemail: '{{ trident_site_adminemail }}'
  when: certbot_adminemail is not defined

- name: Temporarily disable nginx to use port 80/tcp
  service:
    name: nginx
    state: stopped
  notify: restart nginx

- block:
    - name: stat {{ dims_bin }}/certbot-auto
      stat: path='{{ dims_bin }}/certbot-auto'
      register: _certbot
    - name: Ensure certbot-auto is installed
      include: '{{ tasks_path }}/install-certbot-auto.yml'
      when: _certbot.stat.exists == False
  rescue:
    - fail: msg="certbot-auto is not available"

- block:
    - name: Check for existence of /etc/letsencrypt directory
      stat: path='/etc/letsencrypt'
      register: _letsencrypt
    - name: Create temporary directory for generating cert
      file: path=/tmp/letsencrypt state=directory mode=0700
      when: _letsencrypt.stat.exists == False
    - name: Run certbot standalone in Docker container
      shell: >
        docker run -i
        --rm 
        -p 443:443
        -p 80:80
        --name certbot
        -v "/tmp/letsencrypt/etc/letsencrypt:/etc/letsencrypt"
        -v "/tmp/letsencrypt/var/lib/letsencrypt:/var/lib/letsencrypt"
        -v "/tmp/letsencrypt/var/log/letsencrypt:/var/log/letsencrypt"
        certbot/certbot
        certonly
        --noninteractive
        --standalone
        --preferred-challenges tls-sni
        --domain {{ certbot_sitename }}
        --agree-tos
        --email {{ certbot_adminemail }}
        creates=/etc/letsencrypt/live/{{ certbot_sitename }}/cert.pem
      when: _letsencrypt.stat.exists == False
    - name: Remove image
      shell: docker rmi certbot/certbot
      when: _letsencrypt.stat.exists == False
    - name: Install letsencrypt cert directory in /etc
      shell: mv /tmp/letsencrypt/ /etc && tree -up /etc/letsencrypt
      when: _letsencrypt.stat.exists == False
  rescue:
    - fail: msg="certbot-auto could not create certificate"

# vim: ft=ansible :
