---

# File: roles/bootstrap/tasks/packages.yml

- name: Make sure required APT packages are present (Debian)
  apt:
    state: present
    name: [ '{{ packages_install }}' ]
    update_cache: yes
    force: yes
  ignore_errors: yes
  when: ansible_pkg_mgr == "apt"

- name: Make sure required RPM packages are present (RedHat)
  yum:
    state: present
    name: [ '{{ packages_install }}' ]
    update_cache: yes
  ignore_errors: yes
  when: ansible_pkg_mgr == "yum"

- name: Remove broken git from CentOS 6
  yum:
    name: git
    state: absent
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version|int == 6

- name: Ensure wandisco Git installed on CentOS 6
  yum:
    name: [ 'http://opensource.wandisco.com/centos/6/git/x86_64/wandisco-git-release-6-1.noarch.rpm', 'git' ]
    state: present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version|int == 6

  # TODO(dittrich): Implement CoreOS preparation from $GIT/dims-packer/
  #
  # $ tree -P '*.sh' /home/dittrich/dims/git/dims-packer/coreos
  # /home/dittrich/dims/git/dims-packer/coreos
  # ├── 00-ansiblize-coreos.sh
  # ├── get-vers.sh
  # ├── package.sh
  # └── prep.sh
  #
  # 0 directories, 4 files

  # Switch to using iptables like other hosts on CentOS 7
  # See: https://community.rackspace.com/products/f/25/t/4504

- name: Check for presense of firewalld service on CentOS 7
  shell: >
    systemctl | grep -q firewalld
  register: _firewalld
  ignore_errors: yes
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version|int >= 7

- name: Stop and mask firewalld service on CentOS 7
  shell: >
    systemctl stop firewalld &&
    systemctl mask firewalld
  ignore_errors: yes
  when: _firewalld.rc is defined and _firewalld.rc|int == 0

- name: Install and enable iptables-services on CentOS 7
  shell: >
    yum install -y iptables-services &&
    systemctl enable iptables &&
    systemctl enable ip6tables
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version|int >= 7

#- name: Ensure CentOS devtoolset is installed
#  shell: >
#    cd /etc/yum.repos.d &&
#    wget https://people.centos.org/tru/devtools-1.1/devtools-1.1.repo &&
#    yum install -y devtoolset-1.1
#  when: ansible_distribution == "CentOS"

# vim: ft=ansible :
