---

# file: library/post_tasks.yml

- name: POST_TASK - Announce post_task (verbose mode)
  #shell: "echo post_tasks for {{ role_name.stdout }}"
  shell: "echo post_tasks for {{ role_name | quote }}"
  when: verbose

# WARNING: Terse "if" statement ahead!
- name: POST_TASK - List files created by role
  #shell: >
  #       [ -f "{{ deploy_dir }}/CURRENT_ROLE" ] && find /bin /boot /etc /home /lib /lib64 /opt /root /run /sbin /sys /usr /var -newer "{{ deploy_dir }}/CURRENT_ROLE" -ls 2>/dev/null | egrep -v '\.ansible|/run/utmp$|/var/log/|/opt/dims/deploy|/etc/apt' > "{{ deploy_dir }}/createdby-{{ role_name.stdout }}.txt"
  shell: >
          [ -f "{{ deploy_dir | quote }}/CURRENT_ROLE" ] && find /bin /boot /etc /home /lib /lib64 /opt /root /sbin /usr /var -newer "{{ deploy_dir | quote }}/CURRENT_ROLE" -ls | egrep -v '\.ansible|/run/utmp$|/var/log/|/opt/dims/deploy|/etc/apt' > "{{ deploy_dir | quote }}/createdby-{{ role_name }}.txt"
  ignore_errors: yes
  when: listfiles is defined and listfiles

- name: POST_TASK - Remove role deploy directory
  file:
    state: absent
    path: "{{ dims_deploy }}/{{ role_name }}"
  when: role_name is defined

- name: POST_TASK - Delete CURRENT_ROLE file
  file: "path={{ deploy_dir }}/CURRENT_ROLE state=absent"

- name: POST_TASK - Log end of role
  shell: >
    [ -f {{ dims_bin }}/dims.logger ] &&
    {{ dims_bin }}/dims.logger
    --logger-tag ansible-playbook
    --logmon-exchange {{ dims_logmon_exchange|default('devops') }}
    'Ending role: {{ role_name | quote }}'
  ignore_errors: yes

# vim: ft=ansible :
