---

# File: tasks/postfix_basic.yml

- name: Assert dims_fqdn is defined and not null
  assert:
    that:
      - dims_fqdn is defined
      - dims_fqdn != ''

- name: install postfix
  action: yum pkg=postfix state=present
  tags: [ postfix, packages ]

- name: /etc/postfix/main.cf
  action: copy src={{ item }} dest=/etc/postfix/main.cf
  with_first_found:
    - "{{ postfix_maincf }}"
    - "{{ roles_path }}/base/files/postfix/main.cf/main.cf.{{ dims_fqdn }}"
    - "{{ roles_path }}/base/files/postfix/main.cf/main.cf.{{ inventory_hostname }}"
    - "{{ roles_path }}/base/files/postfix/main.cf/main.cf.{{ host_group }}"
    - "{{ roles_path }}/base/files/postfix/main.cf/main.cf.{{ postfix_group }}"
    - "{{ roles_path }}/base/files/postfix/main.cf/main.cf"
  notify:
    - 'restart postfix'
  tags: [ postfix, config ]

- name: Ensure postfix is running and enabled
  service: name=postfix state=started enabled=yes
  tags: [ postfix, config, service ]
