---

aws:
  vars:
    ansible_user: 'ec2-user'
    ansible_port: 22
    ansible_ssh_private_key_file: '{{ lookup("env", "HOME") }}/.ssh/id_rsa'
    _public_key: '{{ ansible_ssh_private_key_file }}.pub'

