---

# File: roles/trident/tasks/main.yml

# This role ensures that the defined version of Trident and
# all of its pre-requisite packages are installed. It also
# ensures that the initial "trident" system administration
# account is present (which is required for all further
# system configuration, creation of trust groups and mailing
# lists, etc.) and that the initial system configuration
# of the web UI is present. Configuration of the primary
# trust group and mailing lists is done in other tasks.

# NOTE: When upgrading versions of Trident, it is important
# that the PostgreSQL tables and users related to Trident
# are deleted before the upgrade. This playbook checks for
# the existence of a PostgreSQL user called 'trident'. If
# that user exists, subsequent steps which setup Trident
# databases and users are skipped. This can be a problem,
# for example, when the Trident program expects new database
# tables, but the database does not have those tables. (We
# had this problem where we couldn't log in because a table
# called 'iptrk' did not exist, and we didn't know why.)
# To get the new tables, the database must be setup from
# scratch. This note may change if the Trident developers
# define an appropriate method for upgrading the database.
# At that time, we will upgrade this playbook.
#
# Until then, run:
#  $ sudo apt-get purge postgresql-*
# before running this playbook.

# NOTE: The trident-perl package is not public at this point.
# You will not have a fully-functional Trident portal without
# it, but will be able to use a full D2 deployment to do
# Trident portal or related content development.

- name: Define trident_install_trident_perl
  set_fact:
    trident_install_trident_perl: false
  when: trident_install_trident_perl is not defined
  tags: [ always ]

- name: Determine user running ansible
  local_action: command whoami
  become: no
  register: _whoami
  tags: [ always ]

- name: Define trident_initial_user_ident
  set_fact:
    trident_initial_user_ident: '{{ _whoami.stdout }}'
  when: trident_initial_user_ident is not defined
  tags: [ always ]

- name: "Determine user's name"
  local_action: command git config user.name
  become: no
  register: _gitusername
  tags: [ always ]

- name: Define trident_initial_user_descr
  set_fact:
    trident_initial_user_descr: '{{ _gitusername.stdout }}'
  when: trident_initial_user_descr is not defined
  tags: [ always ]

- name: "Determine user's email"
  local_action: command git config user.email
  become: no
  register: _gituseremail
  tags: [ always ]

- name: Define trident_initial_user_descr
  set_fact:
    trident_initial_user_email: '{{ _gituseremail.stdout }}'
  when: trident_initial_user_email is not defined
  tags: [ always ]

- name: Assert trident_sysadmin_pass is defined, not null, no spaces
  assert:
    that:
      - trident_sysadmin_pass is defined
      - trident_sysadmin_pass != ''
      - "not trident_sysadmin_pass is search(' ')"
  tags: [ always ]

- name: Assert trident_db_pass is defined and not null
  assert:
    that:
      - trident_db_pass is defined
      - trident_db_pass != ''
  tags: [ always ]

- import_tasks: '{{ tasks_path }}/pre_tasks.yml'
  tags: [ trident-core, config, packages, tests ]

- name: Install required perl libraries
  apt:
    state: present
    name:
     - libdbi-perl
     - libdbd-pg-perl
     - libjson-perl
     - libgnupg-perl
     - haveged
     - libdatetime-format-mail-perl
     - libdatetime-format-pg-perl
     - libgnupg-interface-perl
     - libmail-sendeasy-perl
     - libossp-uuid-perl
     - libmime-tools-perl
    force: yes
  become: yes
  when: trident_install_trident_perl
  tags: [ trident-core, packages ]

- name: Ensure pg_hba.conf present
  template:
    src: '{{ item }}'
    dest: /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0o644
  with_first_found:
    - files:
       - '{{ pghba_conf }}'
       - pg_hba.conf.{{ inventory_hostname }}.j2
       - pg_hba.conf.deployment-{{ deployment }}.j2
       - pg_hba.conf.j2
      paths:
       - '{{ dims_private }}/roles/{{ role_name }}/templates/postgresql/main/'
       - postgresql/main/
  become: yes
  tags: [ trident-core, config ]

# NOTE: Must be restarted before Trident starts so cannot use handler.

- name: Apply configuration change
  service:
    name: postgresql
    state: restarted
  become: yes
  tags: [ trident-core, config ]

# TODO(dittrich): Start of package installation: split here...

# As of March 2018, the Trident release packages are all bundled
# into a single .zip file for simpler downloading. This .zip
# bundle needs to be unpacked to get the constituent packages as
# were created for previous releases. These packages are
# produced by Jenkins jobs if building packages locally
# from source.
#
# Either way, ensure that the following variables are set for
# all elements of the trident_dist_bundle list, which is used
# for ordering of package installation:
# trident_dist_bundle.url
# trident_dist_bundle.sha256sum

- name: Get trident packages from release bundle
  import_tasks: get_bundle.yml
  when:
    - trident_unified_archive_url is defined
    - trident_unified_archive_sha256sum is defined
  tags: [ trident-core, packages ]

- name: Get individual trident packages
  import_tasks: get_individual.yml
  when:
    - trident_unified_archive_url is not defined
    - trident_unified_archive_sha256sum is not defined
  tags: [ trident-core, packages ]

# NOTE: trident-perl package is from private source currently,
# so must retrieve from our cache, not the GitHub download
# directory.

- name: Ensure trident-perl package present
  get_url:
    url: '{{ trident_perl_disturl }}'
    sha256sum: '{{ trident_perl_sha256sum }}'
    dest: '{{ deploy_dir }}/{{ role_name }}/{{ trident_perl_disturl|basename }}'
  become: yes
  when: trident_install_trident_perl
  tags: [ trident-core ]

- name: Ensure trident group present
  group:
    name: trident
    state: present
  become: yes
  tags: [ trident-core ]

- name: Ensure trident user present
  user:
    name: trident
    groups: trident,{{ dims_group }}
    state: present
    append: yes
    createhome: no
  become: yes
  tags: [ trident-core ]

- name: Ensure dims user present in trident group
  user:
    name: '{{ dims_user }}'
    groups: trident
    state: present
    append: yes
    createhome: no
  become: yes
  tags: [ trident-core ]

- name: Ensure postgres user present in trident group
  user:
    name: postgres
    groups: trident
    state: present
    append: yes
    createhome: no
  become: yes
  tags: [ trident-core ]

- name: Debug trident_dist_bundle_dict
  debug:
    var: trident_dist_bundle_dict
    verbosity: 2

- name: Extract URLs
  set_fact:
    urls_list: '{{ urls_list|default([]) + [ item.value.url ] }}'
  with_dict: '{{ trident_dist_bundle_dict }}'
  tags: [ trident-core ]

- name: Debug urls_list
  debug:
    var: urls_list
    verbosity: 2

- name: Define list of files from urls
  set_fact:
    debs_list: '{{ debs_list|default([]) + [ deploy_dir + "/" + role_name + "/" + item|basename ] }}'
  with_items: '{{ urls_list }}'
  when: "not item is search('trident-perl')"
  tags: [ trident-core ]

- name: Debug debs_list
  debug:
    var: debs_list
    verbosity: 2

- name: Ensure core Trident packages are installed
  shell: >
    dpkg --install {{ item }}
  become: yes
  with_items: '{{ debs_list }}'
  notify:
    - 'restart trident'
    - 'restart nginx'
  tags: [ trident-core ]

- name: Ensure trident is started/enabled
  service:
    name: trident
    state: started
    enabled: yes
  become: yes
  tags: [ trident-core ]

# Attempting to install trident-perl without any written instructions.
# Hackety, hackety...

- name: Unpack trident-perl (mail handler) package into /
  shell: >
    dpkg -x {{ deploy_dir }}/{{ role_name }}/{{ trident_perl_archive }} /
  become: yes
  when: trident_install_trident_perl
  tags: [ trident-core ]

- name: Manually extract control files from trident-perl
  shell: >
    dpkg -e {{ deploy_dir }}/{{ role_name }}/{{ trident_perl_archive }}
    {{ deploy_dir }}/{{ role_name }}/trident-perl_DEBIAN
  become: yes
  when: trident_install_trident_perl
  tags: [ trident-core ]

- name: Manually run trident-perl postinst script to install
  shell: >
    sh {{ deploy_dir }}/{{ role_name }}/trident-perl_DEBIAN/postinst
  become: yes
  register: _postinst
  when: trident_install_trident_perl
  tags: [ trident-core ]

- name: Ensure permissions on notify-* scripts
  file:
    path: '/var/lib/trident/library/{{ item }}'
    owner: 'trident'
    group: 'trident'
    mode: 0o755
  with_items:
    - 'cronrun-day'
    - 'cronrun-minute'
    - 'cronrun-week'
    - 'dbck-password'
    - 'fsck-mlkeys'
    - 'fsck-pgpkeys'
    - 'member-get-pgp-key'
    - 'notify-idle'
    - 'notify-stuck'
    - 'notify-unvetted'
    - 'report-unvetted'
    - 'state-mon'
  tags: [ trident-core ]

- name: Get sha256 hash of /var/lib/trident/library/funcs.sh
  stat:
    path: '/var/lib/trident/library/funcs.sh'
    checksum_algorithm: sha256
  register: _funcs_stat
  tags: [ trident-core ]

- name: Determine if it is safe to patch funcs.sh
  assert:
    that:
      - _funcs_stat.stat.checksum == "a9f354a069e1d1b32f3cda39b44747805872cd0a4f8ea7a38c5caff929ef9785"
  tags: [ trident-core ]

- name: Ensure patched /var/lib/trident/library/funcs.sh
  copy:
    src: 'funcs.sh'
    dest: '/var/lib/trident/library/funcs.sh'
    owner: 'trident'
    group: 'trident'
    mode: 0o750
  become: yes
  tags: [ trident-core ]

- name: Define _trident_user_exists
  set_fact:
    _trident_user_exists: '{{ _postinst.stdout|default("") is search("trident user already exists") }}'
  tags: [ trident-core, packages ]

- name: Debug _trident_user_exists
  debug:
    var: _trident_user_exists
    verbosity: 2
  tags: [ trident-core, packages ]

- name: Ensure trident-perl debugging test-email.txt is present
  template:
    src: '{{ item }}'
    dest: /var/lib/trident/library/test-email.txt
    owner: '{{ root_user }}'
    group: '{{ root_group }}'
    mode: 0o644
  with_first_found:
    - files:
       - '{{ trident_test_email }}'
       - test-email.txt.{{ inventory_hostname }}.j2
       - test-email.txt.deployment-{{ deployment }}.j2
       - test-email.txt.j2
      paths:
       - '{{ dims_private }}/roles/{{ role_name }}/templates/'
       - ./
  become: yes
  notify:
    - 'restart trident'
    - 'restart nginx'
  tags: [ trident-core, config ]

- name: Ensure Trident init.d defaults present
  template:
    src: '{{ item }}'
    dest: /etc/default/trident
    owner: '{{ root_user }}'
    group: '{{ root_group }}'
    mode: 0o644
  with_first_found:
    - files:
       - '{{ trident_default }}'
       - trident.{{ inventory_hostname }}.j2
       - trident.deployment-{{ deployment }}.j2
       - trident.j2
      paths:
       - '{{ dims_private }}/roles/{{ role_name }}/templates/trident/default/'
       - trident/default/
  become: yes
  notify:
    - 'restart trident'
    - 'restart nginx'
  tags: [ trident-core, config ]

- name: Ensure /etc/trident/trident.conf is present
  template:
    src: '{{ item }}'
    dest: /etc/trident/trident.conf
    owner: trident
    group: trident
    mode: 0o755
  with_first_found:
    - files:
       - '{{ trident_conf }}'
       - trident.conf.{{ inventory_hostname }}.j2
       - trident.conf.deployment-{{ deployment }}.j2
       - trident.conf.j2
      paths:
       - '{{ dims_private }}/roles/{{ role_name }}/templates/trident/trident.conf/'
       - trident/trident.conf/
  become: yes
  notify:
    - 'restart trident'
    - 'restart nginx'
  # TODO(dittrich): Move this to trident-configure role; use tag for now.
  tags: [ trident-core, trident-configure, config ]

# NOTE: Take care that configuration matches between the
# /etc/trident/trident.conf file and the following file.
# Tight coupling of variable settings.

- name: Ensure /var/lib/trident/siteconfig is present
  template:
    src: '{{ item }}'
    dest: /var/lib/trident/siteconfig
    owner: trident
    group: trident
    mode: 0o755
  with_first_found:
    - files:
       - '{{ siteconfig }}'
       - siteconfig.{{ inventory_hostname }}.j2
       - siteconfig.deployment-{{ deployment }}.j2
       - siteconfig.j2
      paths:
       - '{{ dims_private }}/roles/{{ role_name }}/templates/trident/siteconfig/'
       - trident/siteconfig/
  become: yes
  notify:
    - 'restart trident'
    - 'restart nginx'
  # TODO(dittrich): Move this to trident-configure role; use tag for now.
  tags: [ trident-core, trident-configure, config ]

- name: Ensure /etc/nginx/sites-available/trident present
  template:
    src: '{{ item }}'
    dest: /etc/nginx/sites-available/trident
    owner: '{{ root_user }}'
    group: '{{ root_group }}'
    mode: 0o644
  with_first_found:
    - files:
       - '{{ nginx_conf_trident }}'
       - trident.{{ inventory_hostname }}.j2
       - trident.deployment-{{ deployment }}.j2
       - trident.j2
      paths:
       - '{{ dims_private }}/roles/{{ role_name }}/templates/nginx/sites-available/'
       - nginx/sites-available/
  become: yes
  notify:
    - 'restart trident'
    - 'restart nginx'
  # TODO(dittrich): Move this to trident-configure role; use tag for now.
  tags: [ trident-core, trident-configure, config ]

- name: Ensure /etc/nginx/sites-enabled/trident present
  file:
    src: '/etc/nginx/sites-available/trident'
    dest: '/etc/nginx/sites-enabled/trident'
    state: link
  become: yes
  notify:
    - 'restart trident'
    - 'restart nginx'
  # TODO(dittrich): Move this to trident-configure role; use tag for now.
  tags: [ trident-core, trident-configure, config ]

- name: Ensure trident is restarted
  service:
    name: trident
    state: restarted
  become: yes
  ignore_errors: true
  tags: [ trident-core ]

- name: tcli system get name
  shell: >
    tcli system get name
  register: _tcli_system_get_name
  tags: [ trident-core, trident-configure, config ]

- name: Define _trident_configured
  set_fact:
    _trident_configured: '{{ not (_tcli_system_get_name.stdout == "" or _tcli_system_get_name.stdout is search("Not Configured")) }}'
  tags: [ trident-core, trident-configure, config ]

- name: Debug _trident_configured
  debug:
    var: _trident_configured
    verbosity: 2
  tags: [ trident-core, trident-configure, config ]

- name: Ensure Trident user and database present
  shell: >
    /usr/sbin/tsetup setup_db
  become: yes
  become_user: 'postgres'
  register: _tsetup_db
  changed_when: _tsetup_db.rc == 0
  failed_when: "_tsetup_db.rc != 0 and not _tsetup_db.stdout is search('already exists')"
  tags: [ trident-core ]

- name: Define _trident_initial_setup
  set_fact:
    _trident_initial_setup: "{{ not _tsetup_db.stdout is search('role \"trident\" already exists') }}"
  tags: [ trident-core ]

# Add initial sysadmin user. This step is necessary according to email from
# Linda and Trident documentation (last sentence of "tsetup" section).

- name: Ensure initial sysadmin user present
  shell: >
    /usr/sbin/tsetup adduser trident "{{ trident_sysadmin_pass }}"
  no_log: '{{ _no_log }}'
  become: yes
  become_user: 'postgres'
  register: _tsetup
  when: _trident_initial_setup
  changed_when: _tsetup.rc == 0 and _tsetup.stdout == ''
  failed_when: _tsetup.rc != 0 and not _tsetup.stdout is search('duplicate key value violates unique constraint')
  tags: [ trident-core ]

- name: Ensure Trident user password is set
  shell: >
    /usr/sbin/tsetup setpassword trident "{{ trident_sysadmin_pass }}"
  become: yes
  become_user: 'postgres'
  no_log: '{{ _no_log }}'
  tags: [ trident-core, trident-configure ]

# NOTE(dittrich): All files in /use/share/pitchfork,
# /var/lib/trident, etc. are now included in a backup.
# See tasks/trident_backup.yml

- name: Ensure Trident state directories are present
  file:
    state: directory
    path: '/var/lib/trident/webvar/{{ item }}'
    owner: 'trident'
    group: 'trident'
    mode: 0o750
  become: yes
  with_items:
    - ml_keys
    - pgpkeys
  tags: [ trident-core, trident-configure ]

# On first installation, the system configuration must come from
# one of two sources: a pre-existing backup, or inventory/role
# variables. If trident_backup_restorefrom is set and a backup
# can be located, use it. Otherwise, configure explicitly.

- name: Define default _trident_restore_status
  set_fact:
    _trident_restore_status: false
  tags: [ trident-core ]

# Restore database from a previous backup if enabled and if first
# time.

- import_tasks: '{{ tasks_path }}/trident_restore.yml'
  when:
    - (trident_backup_restorefrom is defined and trident_backup_restorefrom != '')
    - not _trident_user_exists
    - not _trident_configured
  tags: [ trident-core, trident-configure ]

# Configure explicitly if Trident was not configured and could not
# be restored from a backup.

- import_tasks: configure.yml
  when:
    - not _trident_configured
    - not _trident_restore_status
  tags: [ trident-core, trident-configure ]

# Validate Trident is functional

- name: Ensure trident administator can log in
  shell: >
    tcli system login trident "{{ trident_sysadmin_pass }}"
  register: _tcli_login
  no_log: '{{ _no_log }}'
  failed_when: not _tcli_login.stdout is search('Login successful')
  tags: [ trident-core, trident-configure ]

- name: Ensure trident administator is logged out
  shell: >
    tcli system logout
  no_log: '{{ _no_log }}'
  tags: [ trident-core ]

- import_tasks: '{{ tasks_path }}/post_tasks.yml'
  tags: [ trident-core, config, packages, tests ]

# vim: ft=ansible :
