---

# File: inventory/do/nodes.yml

# Make sure the following environment variables are set:
# export DO_API_VERSION="2"
# export DO_API_TOKEN="$YOUR_DO_API_TOKEN"

do:
  vars:
    ansible_user: 'root'
    ansible_port: 22
    ansible_ssh_private_key_file: '{{ lookup("env", "HOME") }}/.ssh/do'
    _public_key: '{{ ansible_ssh_private_key_file }}.pub'
    http_proxy: ''
    https_proxy: ''
    use_letsencrypt: no
    certbot_staging: yes
    certbot_sitename: '{{ inventory_hostname }}'
    do_region: 'sfo1'
    do_ssh_key_id: 'eb:ae:63:b8:92:6f:d1:6c:3c:60:82:9c:b2:f9:73:71'
    do_api_token: '{{ lookup("env", "DO_API_TOKEN") }}'
    droplets:
      - name: 'red'
        region: '{{ do_region }}'
        size: '512mb'
        image_id: 'debian-8-x64'
        ssh_key_id: '{{ do_ssh_key_id }}'
        backups_enabled: 'no'
        module_source: 'floating_ip'
        floating_ip: 'yes'
      - name: 'orange'
        region: '{{ do_region }}'
        size: '512mb'
        image_id: 'debian-8-x64'
        ssh_key_id: '{{ do_ssh_key_id }}'
        backups_enabled: 'no'
      - name: 'purple'
        region: '{{ do_region }}'
        size: '512mb'
        image_id: 'debian-8-x64'
        ssh_key_id: '{{ do_ssh_key_id }}'
        backups_enabled: 'no'
      - name: 'blue'
        region: '{{ do_region }}'
        size: '512mb'
        image_id: 'centos-6-x64'
        #image_id: 'fedora-25-x64'
        ssh_key_id: '{{ do_ssh_key_id }}'
        backups_enabled: 'no'
    artifacts_url: ''
    # Custom rules for default networks
    # (NOTE: Hard-coded device names. Must match above.)
    custom_rules: [
    ]
    zone_iface:
      swarm: 'eth0'
      docker: 'eth0'
      consul: 'eth0'
      rabbitmq: 'eth0'
      private_network: 'eth0'
    net:
      iface:
        'eth0':
          inet: 'static'
          auto_config: ''
          ip: '{{ ansible_host }}'
          network: ''
          netmask: ''
          cidr_bits: ''
          broadcast: ''
          dns_search: '{{ deployment }}'
          dns_servers: ''
          vagrant_net: 'private_network'
  hosts:
    'red.devops.local':
    'blue.devops.local':
      epel_repo_url: 'http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm'
    'orange.devops.local':
      tridentFQDN: '{{ inventory_hostname }}'
    'purple.devops.local':

# vim: ft=ansible :
