---

# File: inventory/swarm/nodes.yml

swarm:
  consul_server: '{{ inventory_hostname in groups.manager }}'
  hosts:
    'red':
    'blue':
    'green':
    'purple':
#  children:
#    manager:
#      vars:
#      hosts:
#    worker:
#      vars:
#      hosts:

# vim: ft=ansible :
