---

# File: roles/rundeck/tasks/main.yml

# Prepare system for using rundeck

- import_tasks: "{{ tasks_path }}/pre_tasks.yml"
  tags: [ rundeck, packages ]

- name: Stop rundeckd daemon
  service: name=rundeckd state=stopped
  become: yes
  notify:
    - 'restart rundeckd'
  ignore_errors: true
  when: ansible_os_family == "Debian"
  tags: [ rundeck ]

- name: Import repository signing key
  apt_key:
    id: '{{ rundeck_gpg_key_id }}'
    url: '{{ rundeck_gpg_key_url }}'
    state: present
  become: yes
  when: ansible_os_family == "Debian"
  tags: [ rundeck, packages ]

- name: Get rundeck deb file 
  get_url:
    url={{ rundeck_dist_url }}/{{ rundeck_artifact }}
    dest={{ dims_deploy }}/{{ role_name }}
    sha256sum={{ rundeck_sha256_sum}}
  become: yes
  when: ansible_os_family == "Debian"
  tags: [ rundeck, packages ]

- name: Install
  shell: "dpkg -i {{ dims_deploy }}/{{ role_name }}/{{ rundeck_artifact }}"
  become: yes
  when: ansible_os_family == "Debian"
  notify:
    - 'restart rundeckd'
  tags: [ rundeck, packages ]

- name: Make realm.properties present
  template:
    src: '{{ item }}'
    dest: /etc/rundeck/realm.properties
    owner: rundeck
    group: rundeck
    mode: 0o640
  with_first_found:
    - files:
        - '{{ realm_properties }}'
        - realm.properties.{{ inventory_hostname }}.j2
        - realm.properties.category-{{ category }}.j2
        - realm.properties.deployment-{{ deployment }}.j2
        - realm.properties.j2
      paths:
        - '{{ dims_private }}/roles/{{ role_name }}/templates/realm.properties/'
        - realm.properties/
  become: yes
  when: ansible_os_family == "Debian"
  notify:
    - 'restart rundeckd'
  tags: [ rundeck, config ]

- name: Ensure rundeckd is running and enabled
  service: name=rundeckd state=started enabled=yes
  become: yes
  tags: [ rundeck, packages ]

- import_tasks: "{{ tasks_path }}/post_tasks.yml"
  tags: [ rundeck, packages ]

# vim: ft=ansible :
