---

# File: inventory/swarm/nodes.yml

swarm:
  vars:
    swarm:
      iface: '{{ swarm_iface }}'
      service_delay_seconds: 30
      services:
        viz:
          nets: []
          ports: [
            {
              host: 9090,
              client: 8080
            },
          ]
          limit_cpu: 0.5
          env_vars: [
            {
              name: 'PORT',
              value: 9090
            },
          ]
          constraints: [
            'node.role == manager',
          ]
          mounts: [
            '/var/run/docker.sock:/var/run/docker.sock',
          ]
          image_name: 'manomarks/visualizer'
          replicas: 1

  hosts:
    'red.devops.local':
    'yellow.devops.local':
    'purple.devops.local':
    'node01.devops.local':
    'node02.devops.local':
    'node03.devops.local':
  children:
    manager:
      hosts:
        'node01.devops.local':
        'node02.devops.local':
        'node03.devops.local':
    worker:
      hosts:
        'red.devops.local':
        'yellow.devops.local':
        'purple.devops.local':

# vim: ft=ansible :
