---

# Local customization variables (remainder are in role's vars/main.yml file)

# These are used by programs outside the consul role, so they are
# defined here for all hosts.

consul_ui_port: 8500
consul_dns_port: 8600
consul_start_join: '[{{ groups.consul|list_to_string_args }}]'
consul_retry_join: '[{{ groups.consul|list_to_string_args }}]'
consul_data_center: '{{ deployment }}'
consul_dns_domain: '{{ deployment }}'
# Type (and mode... not sure why both?) are set based on whether in groups.consul
consul_agent_type: '{{ (inventory_hostname in groups.consul)|ternary("server","client") }}'
consul_mode: '{{ (inventory_hostname in groups.consul)|ternary("server","client") }}'

# vim: ft=ansible :
