---

consul_servers: [
  'node01',
  'node02',
  'node03',
]

consul_startup_method: upstart
consul_version: '0.7.0'
consul_os: 'linux'
consul_artifact: 'consul_{{ consul_version }}_{{ consul_os }}_amd64.zip'
# TODO(dittrich): We use "XXX_url" elsewhere to point to directory, not full URL path to file
consul_dist_url: 'https://releases.hashicorp.com/consul/{{ consul_version }}'
consul_sha256sum: 'b350591af10d7d23514ebaa0565638539900cdb3aaa048f077217c4c46653dd8'
consul_agent_type: 'client'
consul_log_file: '/var/log/consul.log'
consul_bind_interface: 'eth1'
# Default is '0.0.0.0'
consul_bind_address: '0.0.0.0'
consul_inet_interface: 'eth0'
# Default is '127.0.0.1'
consul_client_address: '127.0.0.1'
consul_dns_port: 8600
# TODO(dittrich): This should align with dimscli (it handles fallback)
consul_data_center: 'local'
# TODO(dittrich): Why both "DataCenter" and "DnsDomain"? Shouldn't these be the same?
consul_dns_domain: 'local'
# TODO(dittrich): This should align with dimscli (it handles fallback)
consul_start_join: '192.168.56.21'
# TODO(dittrich): This should align with dimscli (it handles fallback)
consul_retry_join: '192.168.56.21'
# TODO(dittrich): Why both a "Mode" and a "Server" boolean? Isn't second derivable from first? (consulMode != 'client')
consul_mode: 'client'
consul_server: false
consul_data_dir: '/tmp/consul'
# NOTE(mboggess): syslog is for Linux machines; it doesn't play nice with Docker containers.
consul_enable_syslog: false
consul_log_level: 'INFO'
# NOTE(mboggess): If you don't set the client address, then it defaults to 'localhost'
# which messes with the user-data file to bootstrap CoreOS nodes. If you set it to the
# 'eth1' interface, this messes with the RPC services which uses localhost. So, for
# this deployment, we have the "client" services address be 0.0.0.0.
consul_ui_dir: '{{ consul_data_dir }}/dist'

# vim: ft=ansible :
