---

# File: group_vars/all/dims.yml

# This file is intended to serve as the principle site
# configuration file.

verbose: true

deployment: 'local'

dims_kibana_port: 8480
dims_ssh_port: 8422
dims_ssl_port: 8443
# TODO(dittrich): This is a confusing name (left over from old role)
dims_elasticsearch_kibana_port: 9200

# Default browser page
dims_kibana_url: 'http://localhost:{{ dims_kibana_port }}/#/dashboards/UFW_Data.json'
dims_owf_url: 'https://ops.local:{{ dims_ssl_port }}/owf/'
dims_firefox_default_homepage: '{{ dims_owf_url }}'

# file name of Vault password file. Path is created in Vagrantfile.
dims_vault_password_file: '{{ dims_private }}/vault_pass.txt'

dims_ansible_version: 2.3.1.0
dims_ansible_imported_roles:
  - https://github.com/nextrevision/ansible-swarm-playbook
  - https://github.com/uw-dims/ansible-role-jenkins
  - https://github.com/geerlingguy/ansible-role-certbot
  - https://github.com/geerlingguy/ansible-role-nginx

dimscli_version: 0.26.0

dims_timezone: 'US/Pacific'
dims_locale: 'en_US.UTF-8'
dims_etcd2_reboot_strategy: 'off'


# Variables specific to creating host playbook for Ansible provisioning
remoteUser: '{{ ansible_user_id }}'

# Variables for running different Ansible roles
artifact_branch: 'develop'
install_type: 'install'
install_mode: 'system'

# Default to using a local squid proxy on the virtual machine host (e.g., dev laptop)
https_proxy: 'https://10.0.2.2:8000'

# Bash automated testing system
bats_version: 'v0.4.0'


# vim: ft=ansible :
