---

dnsNameserver: '192.168.56.11'
dnsSearch: 'local'
dnsNetworks: [ '192.168.56.0', ]

# TODO(dittrich): Resolve difference between these sets of vars
# DNS settings
#dims_dns_domain: 'local'
#dims_dns_server: 'ns.devops.local'
#dims_dns_ip: ''

dns_zone:
  'local':
    dns_netblock: '192.168.56.0/24'
    dns_in_addr_arpa: '56.168.192'
    nameserver:
      - 'red.devops.local'
      - 'vmhost.devops.local'
    mxserver: 'vmhost.devops.local'
  'consul':
    dns_netblock: '192.168.56.0/24'
    dns_in_addr_arpa:
    nameserver: '{{ groups.manager }}'
    mxserver:

# vim: ft=ansible :
