---

docker_listen_port: 2375
docker_registry: hub.devops.{{ deployment }}:5000

# TODO(dittrich): This should be derived from (a) more global variable(s)
# e.g., docker_insecure_registry_net: '{{ networks["vlan1"].network }}/{{ networks["vlan1"].cidr_bits }}'
docker_insecure_registry_net: 192.168.56.0/24
docker_network_opts: ''
#docker_network_opts: |
  #  -ip={{ hostvars[inventory_hostname].net.iface[hostvars[inventory_hostname].zone_iface['docker']].ip }}
docker_opts: |
  -H=tcp://{{ inventory_hostname }}:2376
  -H=unix:///var/run/docker.sock
  --log-driver json-file
  --log-opt max-size=10m
  --log-opt max-file=10
  --insecure-registry {{ docker_registry }}
  --insecure-registry {{ docker_insecure_registry_net }}

# vim: ft=ansible :
