---

go_version: '1.8.7'
go_archive: 'go{{ go_version }}.linux-amd64.tar.gz'
go_dist_url: 'https://storage.googleapis.com/golang/go{{ go_version }}.linux-amd64.tar.gz'
go_sha256_sum: 'de32e8db3dc030e1448a6ca52d87a1e04ad31c6b212007616cfcc87beb0e4d60'

# vim: ft=ansible :
