---

# Local settings for geerlingguy/nginx role

nginx_version: '1.6.2-5+deb8u3'
nginx_health_check_port: 8888
nginx_worker_processes: 4
nginx_default_port: 80
nginx_default_domain: '{{ category }}.{{ deployment }}'

# vim: ft=ansible :
