---

swarm:
  iface: '{{ swarm_iface }}'
  service_delay_seconds: 30
  services:
    viz:
      nets: []
      ports: [
        {
          host: 9090,
          client: 8080
        },
      ]
      limit_cpu: 0.5
      env_vars: [
        {
          name: 'PORT',
          value: 9090
        },
      ]
      constraints: [
        'node.role == manager',
      ]
      mounts: [
        '/var/run/docker.sock:/var/run/docker.sock',
      ]
      image_name: 'manomarks/visualizer'
      replicas: 1

# vim: ft=ansible :
