---

# File: roles/base/defaults/main.yml

packages_upgrade: false
root_user: root
root_group: root

fail2ban_action: '{{ fail2ban_backend == "systemd"|ternary("%(action_mwj)s", "%(action_mwl)s") }}'
# fail2ban_backend gets set dynamically in tasks/main.yml
fail2ban_banaction: 'iptables-allports'
fail2ban_bantime: 3600 # one hour
fail2ban_chain: 'INPUT'
fail2ban_destemail: 'root@{{ dims_fqdn }}'
fail2ban_filters:
  - 'sshd.conf'
fail2ban_findtime: 600 # 10 minutes
# Items in list can be IP address, CIDR block, or DNS entry
fail2ban_ignoreips:
  - '127.0.0.1/8'
fail2ban_loglevel: 3
#fail2ban_logpath: '/var/log/dims/{{ rsyslog_perhost|default(false)|ternary(dims_fqdn,dims_domain) }}.log'
#fail2ban_logpath: '/var/log/dims/{{ dims_fqdn }}.log'
fail2ban_logpath: '{{ fail2ban_backend == "systemd"| ternary("", "/var/log/auth.log") }}'
fail2ban_logtarget: 'SYSLOG'
fail2ban_maxretry: 3
fail2ban_mta: 'sendmail'
fail2ban_pidfile: '/var/run/fail2ban/fail2ban.pid'
fail2ban_protocol: 'tcp'
fail2ban_sendername: 'Fail2ban'
fail2ban_socket: '/var/run/fail2ban/fail2ban.sock'
fail2ban_services:
  - name: 'sshd'
    port: 22
    service: 'ssh.service'
    filter: 'sshd'
    logpath: '{{ fail2ban_logpath }}'
    bantime: 86400 # one day
    findtime: 86400 # one day
  - name: 'recidive'
    logpath: '{{ fail2ban_logpath }}'
    #bantime: 604800 # one week
    bantime: -1 # forever
    findtime: 604800 # one week
    maxretry: 3
# - name: 'nginx-http-auth'
#   logpath: '{{ fail2ban_logpath }}'
# - name: 'postfix'
#   logpath: '{{ fail2ban_logpath }}'
fail2ban_syslog_facility: 1
fail2ban_syslog_target: '/var/log/fail2ban.log'

# vim: ft=ansible:
