---

# File: roles/base/defaults/main.yml

packages_upgrade: false
root_user: root
root_group: root

fail2ban_loglevel: 3
fail2ban_logtarget: 'SYSLOG'
fail2ban_syslog_target: '/var/log/fail2ban.log'
fail2ban_syslog_facility: 1
fail2ban_socket: '/var/run/fail2ban/fail2ban.sock'
fail2ban_pidfile: '/var/run/fail2ban/fail2ban.pid'
fail2ban_logpath: '/var/log/dims/{{ ansible_fqdn }}.log'
fail2ban_sendername: 'Fail2ban'
# Items in list can be IP address, CIDR block, or DNS entry
fail2ban_ignoreips:
 - '127.0.0.1/8'
fail2ban_bantime: 600
fail2ban_maxretry: 3
fail2ban_findtime: 600
fail2ban_backend: 'polling'
fail2ban_destemail: 'root@{{ ansible_fqdn }}'
fail2ban_banaction: 'iptables-allports'
fail2ban_mta: 'sendmail'
fail2ban_protocol: 'tcp'
fail2ban_chain: 'INPUT'
fail2ban_action: '%(action_mwl)s'
fail2ban_services:
  - name: 'ssh'
    port: 22
    filter: 'sshd'
    logpath: '{{ fail2ban_logpath }}'
  - name: 'recidive'
    logpath: '{{ fail2ban_logpath }}'
    bantime: 604800
    findtime: 86400
    maxretry: 3

#   logpath: '/var/log/auth.log'
# - name: 'nginx-http-auth'
#   logpath: '{{ fail2ban_logpath }}'
# - name: 'postfix'
#   logpath: '{{ fail2ban_logpath }}'
fail2ban_filters:
  - 'sshd.conf'

# vim: ft=ansible:
