---

# File: roles/consul-docker/tasks/main.yml

- import_tasks: "{{ tasks_path }}/pre_tasks.yml"
  tags: [ consul-docker, config ]

- name: Kill any current running instance and remove
  shell: "docker stop consul && docker rm consul"
  become: yes
  ignore_errors: yes
  tags: [ consul-docker ]

- name: Copy script template to target
  template:
    src=start_consul.sh.j2
    dest={{ dims_bin }}/start_consul.sh
    mode=0o770
  become: yes
  tags: [ consul-docker ]

- name: Make Consul data dir on host (for persistence)
  file: path=/consul/data state=directory mode=0o644
  become: yes
  tags: [ consul-docker ]

- name: Generate consul client config
  template:
    src=consul.json.j2
    dest=/etc/consul.d/client/consul.json
    mode=0o644
  become: yes
  tags: [ consul-docker, config ]

- name: Start new instance of consul container
  shell: /bin/bash -c "/opt/dims/bin/start_consul.sh"
  become: yes
  tags: [ consul-docker ]

- import_tasks: "{{ tasks_path }}/post_tasks.yml"
  tags: [ consul-docker, config ]

# vim: ft=ansible :
