---

# File: roles/dns/handlers/main.yml

- include: "{{ handlers_path }}/restart_services.yml"
  static: yes

# TODO(dittrich): This differs from {{ handlers_path }}/restart_services.yml. Why? Which is right?
- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
  become: yes

