---

# File: master.yml
#
# This is the master playbook. It includes all the other playbooks. 
# Usually you would call it with a -t tagname to only run a specific tag 
# over all machines. 

#- import_playbook: ../../playbooks/base_playbook.yml
#  vars:
#    role: ansible-role-ca
#    shelleg:

- import_playbook: playbooks/black.yml
  when: '"live" in groups and "black" in groups["live"]'
- import_playbook: playbooks/red.yml
  when: '"live" in groups and "red" in groups["live"]'
- import_playbook: playbooks/green.yml
  when: '"live" in groups and "green" in groups["live"]'
- import_playbook: playbooks/purple.yml
  when: '"live" in groups and "purple" in groups["live"]'
- import_playbook: playbooks/blue.yml
  when: '"live" in groups and "blue" in groups["live"]'
