---

# File: master.yml
#
# This is the master playbook. It includes all the other playbooks. 
# Usually you would call it with a -t tagname to only run a specific tag 
# over all machines. 

#- import_playbook: ../../playbooks/base_playbook.yml
#  vars:
#    role: ansible-role-ca
#    shelleg:

- import_playbook: playbooks/red.yml
  when: "'red' in groups.do"
- import_playbook: playbooks/green.yml
  when: "'green' in groups.do"
- import_playbook: playbooks/purple.yml
  when: "'purple' in groups.do"
- import_playbook: playbooks/black.yml
  when: "'black' in groups.do"
- import_playbook: playbooks/blue.yml
  when: "'blue' in groups.do"
