---

# File: playbooks/hosts/blue.secretsmgmt.tk.yml

- name: Configure host "blue.secretsmgmt.tk"
  hosts: blue

  vars:
    playbooks_root: "{{ lookup('env', 'PBR') }}"

  vars_files:
   - "{{ playbooks_root }}/vars/global.yml"

  remote_user: "ansible"
  become: yes

  roles:
    - { role: base }
    - { role: postfix }
    - { role: docker }
    - { role: consul }
    - { role: python-virtualenv, use_sphinx: true }
    - { role: nginx }

  handlers:
   - include: "{{ handlers_path }}/restart_services.yml"

# vim: ft=ansible :
