---

# File: playbooks/hosts/black.yml

- name: Configure host "black"
  hosts: black
  gather_facts: true

  vars:
    playbooks_root: "{{ lookup('env', 'PBR') }}"

  vars_files:
   - "{{ playbooks_root }}/vars/global.yml"

  remote_user: "ansible"
  become: yes

  roles:
    - { role: base, packages_upgrade: true }
    - { role: docker }
    - { role: nginx }
    - { role: postfix }
    - { role: consul }
    - { role: python-virtualenv, use_sphinx: true }
    - { role: hashi_vault }

  handlers:
   - import_tasks: "{{ handlers_path }}/restart_services.yml"

# vim: ft=ansible :
