---

# File: playbooks/hosts/blue.yml

- name: Configure host "blue"
  hosts: blue
  gather_facts: true

  vars:
    playbooks_root: "{{ lookup('env', 'PBR') }}"

  vars_files:
   - "{{ playbooks_root }}/vars/global.yml"

  remote_user: "ansible"
  become: yes

  roles:
    - { role: base }
    - { role: docker }
    - { role: nginx }
    - { role: consul }
    - { role: postfix }
    - { role: gosecure }

  handlers:
   - include_tasks: "{{ handlers_path }}/restart_services.yml"

# vim: ft=ansible :
