---

# File: playbooks/hosts/red.yml

- name: Configure host "red"
  hosts: red

  vars:
    playbooks_root: "{{ lookup('env', 'PBR') }}"

  vars_files:
   - "{{ playbooks_root }}/vars/global.yml"

  remote_user: "ansible"
  become: yes

  roles:
    - { role: base }
    - { role: nginx }
    - { role: postfix }
    - { role: docker }
    - { role: consul }
    - { role: python-virtualenv, use_sphinx: false }
    - { role: rabbitmq }
    - { role: postfix }

  handlers:
   - include: "{{ handlers_path }}/restart_services.yml"

# vim: ft=ansible :
