---

# File: playbooks/hosts/yellow.yml

- name: Configure host "yellow"
  hosts: yellow
  gather_facts: true

  vars:
    playbooks_root: "{{ lookup('env', 'PBR') }}"
    # Using letsencrypt requires hacking some other variables (for now).

  vars_files:
   - "{{ playbooks_root }}/vars/global.yml"

  remote_user: "ansible"
  become: yes

  roles:
    - { role: base }
    - { role: docker }
    - { role: nginx }
    - { role: postfix }
    - { role: consul }
    - { role: python-virtualenv, use_sphinx: false }
    - { role: postgresql }
    - { role: trident-core }
    - { role: trident-configure }

  handlers:
   - include: "{{ handlers_path }}/restart_services.yml"

# vim: ft=ansible :
