---

# File: roles/squid-proxy/tasks/main.yml

# TODO(dittrich): Beware, this role was never completed. Remove?

- import_tasks: "{{ tasks_path }}/pre_tasks.yml"
  tags: [ squid-proxy, config ]

#
# Initialize
#

- name: Stop squid service if running - ignore errors
  service: "name={{ squidBasename }} state=stopped"
  become: yes
  ignore_errors: true
  tags: [ squid-proxy ]

#
# Configure
#

#
# Start
#

- name: Stop and remove old containers
  shell: "docker stop {{ squidContainerName }} && docker rm {{ squidContainerName }}"
  ignore_errors: yes
  tags: [ squid-proxy ]

- import_tasks: "{{ tasks_path }}/post_tasks.yml"
  tags: [ squid-proxy, config ]

# vim: ft=ansible :
