---

# File: inventory/do/nodes.yml

# Make sure the following environment variables are set:
# export DO_API_VERSION="2"
# export DO_API_TOKEN="$YOUR_DO_API_TOKEN"

do:
  vars:
    ansible_user: 'root'
    ansible_port: 22
    ansible_ssh_private_key_file: '{{ lookup("env", "TF_VAR_private_key") }}'
    artifacts_url: ''
    _public_key: '{{ ansible_ssh_private_key_file }}.pub'
    http_proxy: ''
    https_proxy: ''
    certbot_staging: no
    certbot_sitename: '{{ ansible_fqdn }}'
    certbot_backup_dir: '{{ dims_backups }}/{{ ansible_fqdn }}'
    certbot_backup_restorefrom: 'latest'
    certbot_save_backups: yes
    dims_secrets_dir: '{{ lookup("env", "HOME") }}/.secrets/digital-ocean'
    dims_keys: '{{ lookup("env", "HOME") }}/.secrets/digital-ocean/keys'
    dims_backups: '{{ lookup("env", "HOME") }}/.secrets/digital-ocean/backups'
    do_ssh_key_id: '{{ lookup("env", "TF_VAR_ssh_fingerprint") }}'
    do_api_token: '{{ lookup("env", "DO_API_TOKEN") }}'
    do_region: '{{ lookup("env", "TF_VAR_region") }}'
    do_droplets:
      - name: 'red'
        region: '{{ do_region }}'
        size: '512mb'
        image_id: 'debian-8-x64'
        ssh_key_id: '{{ do_ssh_key_id }}'
        backups_enabled: 'no'
        module_source: 'floating_ip'
        floating_ip: 'yes'
      - name: 'green'
        region: '{{ do_region }}'
        size: '2gb'
        image_id: 'debian-8-x64'
        ssh_key_id: '{{ do_ssh_key_id }}'
        backups_enabled: 'no'
      - name: 'purple'
        region: '{{ do_region }}'
        size: '512mb'
        image_id: 'debian-8-x64'
        ssh_key_id: '{{ do_ssh_key_id }}'
        backups_enabled: 'no'
      - name: 'blue'
        region: '{{ do_region }}'
        size: '512mb'
        image_id: 'centos-7-x64'
        #image_id: 'fedora-27-x64'
        ssh_key_id: '{{ do_ssh_key_id }}'
        backups_enabled: 'no'
    dns_a_ttl: 360
    dns_cname:
      red:
        - mail
        - rabbitmq
      green:
        - jenkins
      purple:
        - trident
    dns_cname_ttl: 360
    dns_subdomains: '' # e.g., '.subdomain'
    dns_txt:
      # https://scaron.info/blog/debian-mail-spf-dkim.html
      - name: '_dmarc'
        value: 'v=DMARC1; p=none'
      # http://opendkim.org/opendkim-README
      - name: '_report._domainkey'
        value: 'ra=root'
      # https://app.dmarcanalyzer.com/dns/dkim?simple=1
      - name: '{{ opendkim_selector }}._domainkey'
        value: 'v=DKIM1; h=sha256; k=rsa; s=email; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApZRpNnjWsbqldIIFFJQ+8VEgO4EVVbTFL7fmYB/BAOGdbNeCYyDNcM7b/1SVjucrrWJgrUvYlQhydI1i33BN4veLgLjUE5WJg5FIT2d0wk1wawQ0g/rXgUTmhz2ouWSSE9DFsHGPmR7Pi+6w3BNJU12Xtd7RiXw4g567g/uniQ2TrMkFfxtVSwOJ6bPNvNBxVzPJN7pRVh3kdVUFnnUY9BuC7O6debIOi3+QKdjocpCcLVXpHnJnKihTgp04JnvTYctxlVpWC8vr1D0JNgWlmjIWjr5KtrzG4fSVT5ZKFplLFHYI4jXCgbaQgxWO9d0IHSmPAfvObVKC0STNQx3AMQIDAQAB'
      # https://www.spfwizard.net/
      - name: '_spf'
        value: 'v=spf1 mx ptr ip4:{{ hostvars["red"].ansible_default_ipv4.address|ipaddr("host") }} ip4:{{ hostvars["green"].ansible_default_ipv4.address|ipaddr("host") }} ip4:{{ hostvars["purple"].ansible_default_ipv4.address|ipaddr("host") }} ~all'
        #value: 'v=spf1 mx a ptr ~all'
      - name: '@'
        value: 'v=spf1 include:_spf.{{ dims_domain }} ~all'
    dns_txt_ttl: 360
    dns_mx:
      - name: '_spf'
        value: '{{ hostvars[groups.postfix_mx.0].ansible_fqdn|default("mail" + dims_domain) }}'
        priority: 10
      - name: '@'
        value: '{{ hostvars[groups.postfix_mx.0].ansible_fqdn|default("mail" + dims_domain) }}'
        priority: 10
    dns_mx_ttl: 360
    # Custom rules for default networks
    # (NOTE: Hard-coded device names. Must match above.)
    zone_iface:
      swarm: 'eth0'
      docker: 'eth0'
      consul: 'eth0'
      rabbitmq: 'eth0'
      private_network: 'eth0'
    net:
      iface:
        'eth0':
          inet: 'static'
          auto_config: ''
          ip: '{{ ansible_host }}'
          network: ''
          netmask: ''
          cidr_bits: ''
          broadcast: ''
          dns_search: '{{ deployment }}'
          dns_servers: ''
          vagrant_net: 'private_network'
    use_letsencrypt: yes
  hosts:
    'red':
      custom_rules: [
        '-A TCP -m conntrack --ctstate NEW -m tcp -p tcp --dport {{ nginx_ssl_port }} -j ACCEPT',
        '-A TCP -m conntrack --ctstate NEW -m tcp -p tcp --dport {{ rabbitmq_ssl_listen_port }} -j ACCEPT',
        ]
    #'blue':
    #  epel_repo_url: 'http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm'
    'green':
      tridentFQDN: '{{ ansible_fqdn }}'
    'purple':
      tridentFQDN: '{{ ansible_fqdn }}'
      trident_perl_disturl: 'https://staff.washington.edu/dittrich/{{ trident_perl_archive }}'

# vim: ft=ansible :
