---

# File: roles/rabbitmq/defaults/main.yml

_rabbitmq_listen_address: '127.0.0.1'
_rabbitmq_apt_repo: 'deb http://www.rabbitmq.com/debian/ testing main'
_rabbitmq_apt_key: 'https://www.rabbitmq.com/rabbitmq-release-signing-key.asc'
_rabbitmq_plugins:
  - rabbitmq_management
  - rabbitmq_tracing
  - rabbitmq_federation
  - rabbitmq_shovel
_rabbitmq_etc_default: |
  ulimit -n 1024
_rabbitmq_environment: false
_rabbitmq_reverse_lookups: true
  

#rabbitmq_cacert     : "files/rabbitmq_cacert.pem"
#rabbitmq_server_key : "files/rabbitmq_server_key.pem"
#rabbitmq_server_cert: "files/rabbitmq_server_cert.pem"

# Assumes using "nginx" role to simplify handling SSL certs
rabbitmq_listen_address: ''
rabbitmq_listen_port: 5672
rabbitmq_ssl_listen_address: '0.0.0.0'
rabbitmq_ssl_listen_port: 5671
rabbitmq_ssl_cacertfile: "/etc/rabbitmq/ssl/{{ rabbitmq_cacert | basename }}"
rabbitmq_ssl_certfile: "/etc/rabbitmq/ssl/{{ rabbitmq_server_cert | basename }}"
rabbitmq_ssl_keyfile: "/etc/rabbitmq/ssl/{{ rabbitmq_server_key | basename }}"
rabbitmq_ssl_fail_if_no_peer_cert: "true"

# ft=ansible :
