---

# File: roles/rabbitmq-docker/tasks/main.yml

- include: "{{ tasks_path }}/ansible2check.yml"
  tags: [ always ]

- include: "{{ tasks_path }}/pre_tasks.yml"
  tags: [ rabbitmq-docker ]

- name: Kill any current running instance and remove
  shell: "docker stop rabbitmq && docker rm rabbitmq"
  sudo: yes
  ignore_errors: yes
  tags: [ rabbitmq-docker ]

# TODO(mboggess): Figure out this scripts's mode
- name: Copy script template to target
  template: src=start_rabbitmq.sh.j2 dest=/tmp/start_rabbitmq.sh mode=0774
  tags: [ rabbitmq-docker ]

- name: Start new instance of rabbitmq container
  shell: /bin/bash -c "/tmp/start_rabbitmq.sh"
  sudo: yes
  tags: [ rabbitmq-docker ]

- include: "{{ tasks_path }}/post_tasks.yml"
  tags: [ rabbitmq-docker ]

# vim: ft=ansible :
