---

# File: roles/debug/tasks/main.yml

# Simple role to dump variables for debugging using
# just one conditional. To invoke, use "-e debug=true"
# or "debug: true" somewhere in the inventory and ensure
# this role is included in the appropriate playbook.

- import_tasks: "{{ tasks_path }}/debug-dump-vars.yml"
  tags: [ always ]

# vim: ft=ansible :
