---

# File: inventory/ca/nodes.yml

# This inventory holds variables and hosts for handling self-signed
# certificates for development of SSL-enabled services. A production
# system should use a service like Letsencrypt for internet-facing
# systems.

ca_certs:
  vars:
    # For ansible-role-ca
    ca_certs_dir: '/usr/share/ca-certs'
    # Customization of certs
    ca_rootca_password: '{{ lookup("psec", "secrets get ca_rootca_password") }}'
    ca_distribution_certs_dir: '{{ dims_private }}/files/certs'
    ca_country: '{{ lookup("psec", "secrets get ca_country") }}'
    ca_state: '{{ lookup("psec", "secrets get ca_state") }}'
    ca_locality: '{{ lookup("psec", "secrets get ca_locality") }}'
    ca_organization: '{{ lookup("psec", "secrets get ca_organization") }}'
    ca_domain: '{{ lookup("psec", "secrets get ca_domain") }}'
    ca_organizationalunit: '{{ lookup("psec", "secrets get ca_organizationalunit") }}'
    ca_commonname: '{{ lookup("psec", "secrets get ca_commonname") }}'
    ca_email: '{{ lookup("psec", "secrets get ca_email") }}'
# Set hosts in a local inventory.
#  hosts:
#    'red':
#    'blue':
#    'purple':
#    'green':
#  children:
#    infra:
#      hosts:
#        'red':
#          # Control of sub-tasks
#          ca_init: false
#          ca_certify_nodes: false
#          ca_wildcard: false
#          ca_fetch_keys: false
#          ca_distribute_keys: false
#    instances:
#      hosts:
#        'red':
#        'blue':
#        'green':
#        'purple':

# vim: ft=ansible :
