---

# File: host_vars/vmhost.devops.local.yml

name: "vmhost"
ansible_host: 127.0.0.1
ansible_connection: local
https_proxy: 'https://127.0.0.1:8000'

eth1:
  ip: "192.168.56.1"

# vim: ft=ansible :
