---

# File: host_vars/yellow.devops.local.yml

name: "yellow"
PORT: "22"

dims_users: [ 'dittrich', 'mboggess', ]

tcp_ports: [ 53, 2377, 4789, 7946, 9999 ]
udp_ports: [ 53, 4789, 7946 ]

eth1:
  ip: "192.168.56.13"
  auto_config: "true"
eth2:
  ip: "10.168.56.13"
  auto_config: "false"

box_baseos: "debian"
box_osversion: "8.5.0"
box_osnick: "jessie"
box_type: "server"
iso_source: "file:///vm/cache/isos"
iso_arch: "amd64"
iso_checksum_type: "sha256"
iso_checksum: "ad4e8c27c561ad8248d5ebc1d36eb172f884057bfeb2c22ead823f59fa8c3dff"  # debian-8.5.0-amd64-netinst.iso
ssh_pass: "{{ vault_ssh_pass }}"
installDesktop: ""
headless: false

# Trident vars
# TODO(dittrich): This should be a CNAME record named "trident.devops.develop"
tridentFQDN: "yellow.devops.local"
# TODO(dittrich): Should use a DNS lookup to get the IP, not two variables (one name, one IP)
tridentIP: "192.168.56.13"

# vim: ft=ansible :
