---

# File: inventory/swarm/nodes.yml

swarm:
  vars:
    consul_server: '{{ inventory_hostname in groups.manager }}'
# Set hosts in a local inventory.
#  hosts:
#    'red':
#    'blue':
#    'green':
#    'purple':
#  children:
#    manager:
#    worker:

# vim: ft=ansible :
