---

# requires --extra-vars="target=hostspec"

- name: reboot hosts
  hosts: "{{ target }}"
  gather_facts: False
  user: root
  serial: 1

  tasks:
  - name: Reboot host
    reboot:
      connect_timeout: '{{ connect_timeout|default(3600) }}'
    register: reboot

  - name: Debug reboot result
    debug:
      msg: 'Rebooting {{ hostvars[inventory_hostname].dims_fqdn }} {{ reboot.rebooted|ternary("succeed", "failed") }} in {{ reboot.elapsed }} seconds'

  - name: Sync time
    command: 'ntpdate -u {{ ntp_server|default("1.rhel.pool.ntp.org") }}'
    register: ntpdate

  - name: Debug time sync result
    debug:
      msg: 'Clock on {{ hostvars[inventory_hostname].dims_fqdn }}: {{ ntpdate.stdout.split(":")[3] }}'


# vim: ft=ansible :
