---

# This playbook supports stand-alone use of the postgresql_restore.yml
# task file to restore the database of a Trident portal installed
# using DIMS Ansible playbooks and inventory. The tasks have been
# separated to allow their use from within roles.

- name: Restore trident postgresql database
  hosts: '{{ host }}'
  gather_facts: true
  user: root
  vars_files:
    - "{{ playbooks_root }}/vars/global.yml"
  tasks:
    - import_tasks: '{{ tasks_path }}/postgresql_restore.yml'

# vim: ft=ansible :
