---

# File: tasks/visualize-swarm.yml

- hosts: manager
  become: true

  vars_files:
    - "{{ playbooks_root }}/vars/global.yml"

  tasks:
    # Determine the swarm status of each production node.
    # If any production node is not part of the swarm,
    # immediately fail.
    - name: determine swarm status
      shell: >
        docker info | egrep '^Swarm: ' | cut -d ' ' -f2
      register: swarm_status

    - fail:
        msg: "Node {{ item }} not in swarm"
      with_items: "{{ ansible_play_hosts | default(play_hosts) }}"
      when: "'active' not in hostvars[item].swarm_status.stdout_lines"
      run_once: true

    # Services must be started via a manager node
    - name: Pick random host from manager group
      set_fact:
        random_manager: "{{ groups.manager | random }}"
      run_once: true

    # Create the service on a manager node (via a manager node)
    - name: Check if service is running
      shell: >
        docker service ls | grep viz
      register: results
      run_once: true
      delegate_to: "{{ random_manager }}"
      ignore_errors: yes

    - debug: var=results
      run_once: true
      delegate_to: "{{ random_manager }}"

    - name: Make stack app directory present
      file:
        path: "{{ dims_etc }}/stack/viz"
        state: directory
        mode: "{{ mode_0755 }}"
      run_once: true
      delegate_to: "{{ random_manager }}"
      when: results.rc == 1

    - name: Make stack app docker-compose file present
      template:
        src: "{{ playbooks_root }}/stack/viz/docker-compose.yml.j2"
        dest: "{{ dims_etc }}/stack/viz/docker-compose.yml"
        owner: "{{ dims_user }}"
        group: "{{ dims_group }}"
        mode: "{{ mode_0755 }}"
      run_once: true
      delegate_to: "{{ random_manager }}"
      when: results.rc == 1

    - name: Deploy the stack on a node
      shell: >
        docker stack deploy -c {{ dims_bin }}/stack/viz/docker-compose.yml viz
      run_once: true
      delegate_to: "{{ random_manager }}"
      when: results.rc == 1

    - name: Pause to allow service to come up
      wait_for:
        port: "{{ swarm.services.viz.ports.0.host }}"
        delay: "{{ swarm.service_delay_seconds }}"
      run_once: true
      delegate_to: "{{ random_manager }}"
      when: results.rc == 1

# vim: ft=ansible :
