---

# File: playbooks/hosts/blue14.devops.local.yml

- name: Dump all vars if debug enabled
  hosts: blue14.devops.local

  vars_files:
   - "{{ playbooks_root }}/vars/global.yml"
   - "{{ playbooks_root }}/vars/xenial.yml"

  remote_user: "ansible"

  tasks:
   - include: "{{ tasks }}/debug-dump-vars.yml"

- name: Configure host "blue14.devops.local"
  hosts: blue14.devops.local

  vars_files:
   - "{{ playbooks_root }}/vars/global.yml"
   - "{{ playbooks_root }}/vars/xenial.yml"

  remote_user: "ansible"
  sudo: yes

  roles:
    - { role: base }
    - { role: hosts }
    - { role: dims-ci-utils }
    - { role: postfix }
    - { role: python-virtualenv, use_sphinx: true }
    - { role: docker }
    - { role: consul }
    - { role: vagrant }
    - { role: pycharm }
    - { role: byobu }

  handlers:
   - include: "{{ handlers }}/restart_services.yml"

