---

# File: playbooks/hosts/blue16.devops.local.yml

- name: Configure host "blue16.devops.local"
  hosts: blue16.devops.local

  vars:
    playbooks_root: "{{ lookup('env', 'PBR') }}"

  vars_files:
   - "{{ playbooks_root }}/vars/global.yml"
   - "{{ playbooks_root }}/vars/xenial.yml"

  remote_user: "ansible"
  become: yes

  roles:
    - { role: debug }
    - { role: base }
    - { role: hosts }
    - { role: dims-ci-utils }
    - { role: postfix }
    - { role: python-virtualenv, use_sphinx: true }
    - { role: docker }
    - { role: consul, consul_startup_method: "supervisor" }
    - { role: vagrant }
    - { role: pycharm }
    - { role: byobu }

  handlers:
   - include: "{{ handlers_path }}/restart_services.yml"
