---

# File: playbooks/hosts/hub.devops.local.yml
#
# Host file for provisioning development/testing using host "hub" (application server).
#

- name: Dump all vars if debug enabled
  hosts: hub.devops.local

  vars:
    playbooks_root: "{{ lookup('env', 'PBR') }}"

  vars_files:
   - "{{ playbooks_root }}/vars/global.yml"
   - "{{ playbooks_root }}/vars/{{ ansible_distribution_release }}.yml"

  remote_user: "ansible"

  tasks:
   - include: "{{ tasks }}/debug-dump-vars.yml"

- name: Configure host "hub.devops.local"
  hosts: hub.devops.local

  vars:
    playbooks_root: "{{ lookup('env', 'PBR') }}"

  vars_files:
   - "{{ playbooks_root }}/vars/global.yml"
   - "{{ playbooks_root }}/vars/{{ ansible_distribution_release }}.yml"

  remote_user: "ansible"
  sudo: yes

  roles:
    - { role: base }
    - { role: hosts }
    - { role: dims-ci-utils }
    - { role: postfix }
    - { role: python-virtualenv, use_sphinx: true }
    - { role: docker }
    - { role: consul }

  handlers:
   - include: "{{ handlers }}/restart_services.yml"

