---

# File: playbooks/hosts/node01.devops.local.yml

- name: Configure host "node01.devops.local"
  hosts: node01.devops.local

  vars:
    playbooks_root: "{{ lookup('env', 'PBR') }}"

  vars_files:
   - "{{ playbooks_root }}/vars/global.yml"

  remote_user: "ansible"
  become: yes

  roles:
    - { role: debug }
    - { role: base }
    - { role: docker }
    - { role: consul }

  handlers:
   - include: "{{ handlers_path }}/restart_services.yml"

# vim: ft=ansible :
