---

# File: playbooks/hosts/node03.devops.local.yml

- name: Dump all vars if debug enabled
  hosts: node03.devops.local

  vars_files:
   - "{{ playbooks_root }}/vars/global.yml"
   - "{{ playbooks_root }}/vars/coreos.yml"

  remote_user: "ansible"

  tasks:
   - include: "{{ tasks }}/debug-dump-vars.yml"

- name: Configure host "node03.devops.local"
  hosts: node03.devops.local

  vars_files:
   - "{{ playbooks_root }}/vars/global.yml"
   - "{{ playbooks_root }}/vars/coreos.yml"

  remote_user: "ansible"
  sudo: yes

  roles:
    - { role: base }
    - { role: docker }
    - { role: consul }

  handlers:
   - include: "{{ handlers }}/restart_services.yml"
