---

# File: playbooks/hosts/node01.devops.local.yml

- name: Dump all vars if debug enabled
  hosts: node01.devops.local

  vars:
    playbooks_root: "{{ lookup('env', 'PBR') }}"

  vars_files:
   - "{{ playbooks_root }}/vars/global.yml"
   - "{{ playbooks_root }}/vars/coreos.yml"

  remote_user: "ansible"

  tasks:
   - include: "{{ tasks_path }}/debug-dump-vars.yml"

- name: Configure host "node01.devops.local"
  hosts: node01.devops.local

  vars:
    playbooks_root: "{{ lookup('env', 'PBR') }}"

  vars_files:
   - "{{ playbooks_root }}/vars/global.yml"
   - "{{ playbooks_root }}/vars/coreos.yml"

  remote_user: "ansible"
  become: yes

  roles:
    - { role: base }
    - { role: docker }
    - { role: consul }

  handlers:
   - include: "{{ handlers_path }}/restart_services.yml"
