---

# File: playbooks/hosts/red.devops.local.yml

- name: Configure host "red.devops.local"
  hosts: red.devops.local

  vars:
    playbooks_root: "{{ lookup('env', 'PBR') }}"

  vars_files:
   - "{{ playbooks_root }}/vars/global.yml"
   - "{{ playbooks_root }}/vars/trusty.yml"

  remote_user: "ansible"
  become: yes

  roles:
    - { role: debug }
    - { role: base }
    - { role: hosts }
    - { role: nginx }
    - { role: dims-ci-utils }
    - { role: dns, zones: ['local', 'consul'] }
    - { role: python-virtualenv, use_sphinx: false, https_proxy: "https://10.0.2.2:8000" }
    - { role: postfix }
    - { role: docker }
    - { role: consul }

  handlers:
   - include: "{{ handlers_path }}/restart_services.yml"

# vim: ft=ansible :
