---

# File: playbooks/hosts/vmhost.devops.local.yml

- name: Configure host "vmhost.devops.local"
  hosts: vmhost.devops.local

  vars:
    playbooks_root: "{{ lookup('env', 'PBR') }}"

  vars_files:
   - "{{ playbooks_root }}/vars/global.yml"
   - "{{ playbooks_root }}/vars/trusty.yml"

  remote_user: "ansible"
  become: yes

  roles:
    - { role: debug }

  handlers:
   - include: "{{ handlers_path }}/restart_services.yml"
